### ISSUE TITLE
integration tests: scenario to ua enable livepatch on trusty image with HWE kernel installed

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1017]
enabling livepatch requires HWE kernel 4.4 or greater.
We need an integration test which can create a base trust image that has the HWE kernel installed
per https://wiki.ubuntu.com/Kernel/LTSEnablementStack

note: only qemu kvm machines will allow enabling livepatch. Livepatch is not allowed on containers.

May involve extensions to lxd-vm support in pycloudlib

**Comment by blackboxsw** [comment]
Leaving this out of milestone 25 as we can manually cover the livepatch vm test for SRU into trusty until we get around to this

**Comment by orndorffgrant** [comment]
We're no longer supporting trusty in our integration tests and we think our livepatch tests for other releases are sufficient. Please re-open if you disagree.
