### ISSUE TITLE
Add cis-audit support on Xenial and Bionic

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1030]
Support for CIS-audit in UA Client requires:

- [ ] tools/refresh-keyrings to add proper keyring on a trusty for cis-audit repository https://launchpad.net/~ubuntu-advantage/+archive/ubuntu/security-benchmarks
- [ ] Confirm ua-contracts to provide support matrix for cis-audit on Xenial & Bionic
- [ ] Validate oscap auditing script properly alerts about auditing failures
- [ ] `ua enable cis-audit` installs cis-audit deb and informs user how to use the tooling
- [ ] Support oscap alias subcommand  `ua cis-audit server --level [1|2]` to run audit scan
- [ ] Support oscap alias subcommand  `ua cis-audit workstation --level [1|2]` to run audit scan
- [ ] `ua disable cis-audit`properly removes cis-audit deb and informs the user about the presence of modified files

**Comment by mitechie** [comment]
We're not going to wrap the tooling just get it set up and ready on the user's system.

**Comment by lucasmoura** [comment]
Feature added on: #1276
