### ISSUE TITLE
apt-get source doesn't work with ESM packages

### ISSUE THREAD

**Issue by mitechie** [canonical/ubuntu-advantage-client#1042]
Let's make sure you can apt-get source when ESM is enabled for the source packages of ESM provided debs. 

Paste of folks trying it out: https://pastebin.canonical.com/p/yYRSJRS7qV/

**Comment by mitechie** [comment]
@morlino 
yeah, I believe it works if you have the ppa with credentials configured in your deb-src lines. It seems to be how umt download gets sources. but if I use `deb-src https://esm.ubuntu.com/ubuntu trusty-infra-security main` it fails

**Comment by blackboxsw** [comment]
@mitechie and @markmorlino, Apt credentials are stored root readonly in /etc/apt/auth.d/90ubuntu-advantage.... so non-root users will not be able to see these credentials to download sources via apt-get source X.   Running sudo apt-get source will work here.

**Comment by blackboxsw** [comment]
It's a bit of a product question whether we should claim to support direct download of source packages for authenticated esm packages non-root users. Will need to discuss this with the product owners here.

**Comment by markmorlino** [comment]
I don't think it would have occured to me that it needed to run as root but yes, after uncommenting the deb-src lines `sudo apt-get source` does work to download source packages on an esm enabled trusty vm.

**Comment by blackboxsw** [comment]
Since generally there is access to the source using `sudo` I suggest we close this issue, and if there is a use case that requires non-sudo access to source, then we can explore that as a feature request

**Comment by panlinux** [comment]
One option would be to use a group, and set the permissions of the file hosting the credentials to 0640. Initially I thought we could use `adm`, as the first user added to an ubuntu system will be a member of that group, but it might be best to create an `ubundu-advantage` group and let administrators decide who should be able to see the ua credentials.
