### ISSUE TITLE
xenial/bionic unsupported upgrade path from ua-tools 10ubuntu0.16.04.1 to >= 20.2

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1044]
in ubuntu-advantage-tools packaging we introduced a breaking change in packaging for v 20.2.

This results in inability to upgrade from stock ubuntu-advantage-tools 10ubuntu0.16.0.4.1(xenial) or 17(bionic) to 20.2 or later.

Recording this issue so we can confirm a product decision **NOT** to support this upgrade path on official release of ubuntu-advantage-tools to Xenial and Bionic

```
sudo dpkg -i /var/tmp/ubuntu-advantage-pro_20.4_amd64.deb 
Selecting previously unselected package ubuntu-advantage-pro.
dpkg: regarding .../ubuntu-advantage-pro_20.4_amd64.deb containing ubuntu-advantage-pro:
 ubuntu-advantage-pro breaks ubuntu-advantage-tools (<< 20.2)
  ubuntu-advantage-tools (version 10ubuntu0.16.04.1) is present and installed.

dpkg: error processing archive /var/tmp/ubuntu-advantage-pro_20.4_amd64.deb (--install):
 installing ubuntu-advantage-pro would break ubuntu-advantage-tools, and
 deconfiguration is not permitted (--auto-deconfigure might help)
Errors were encountered while processing:
 /var/tmp/ubuntu-advantage-pro_20.4_amd64.deb
```

**Comment by patriciadomin** [comment]
Chad, this is happening only when you are trying to install `-pro`. package.
I do not see this issue installing `ubuntu-advantage-tools_20.4_amd64.deb`  neither on xenial or bionic.
```
...
Unpacking ubuntu-advantage-tools (20.4) over (17) ...
```

**Comment by blackboxsw** [comment]
Confirmed on latest version 25.0 also does not exhibit this issue from stock ubuntu-advantage-tools version in Xenial-updates and/or bionic-updates. Thanks @patriciadomin . I'm closing this issue as invalid
