### ISSUE TITLE
ua enable does not have tab completion for root user

### ISSUE THREAD

**Issue by mitechie** [canonical/ubuntu-advantage-client#1060]
Per the title, we should have a list of options if I `ua enable <tab>`

**Comment by blackboxsw** [comment]
@mitechie I'd say low-hanging fruit optional goal for milestone 25.0, but not blocker. Is that right?

**Comment by mitechie** [comment]
Sounds like a plan ty

**Comment by mitechie** [comment]
This is just me on zsh I guess. It's a nice to have for zsh users as well but understand it's a lower priority.

**Comment by orndorffgrant** [comment]
Tracking in SC-1092

**Comment by renanrodrigo** [comment]
While working on #2330 , I realized it works fine. But the root user must enable autocomplete in their shells (`bash_completion`, for instance). Once the shell is properly configured for autocomplete, then it works. I am closing this issue.
