### ISSUE TITLE
move travis-ci from Bionic to Focal

### ISSUE THREAD

**Issue by patriciadomin** [canonical/ubuntu-advantage-client#1072]
Travis docs does not point to Focal yet: https://docs.travis-ci.com/user/reference/linux/
but it does work. My previous test it was still a development branch image:
`Description:	Ubuntu Focal Fossa (development branch)`, It is not anymore.
```
Build dist: focal
Build id: 692658455
Job id: 692658456
Runtime kernel version: 5.4.0-1011-gcp
travis-build version: 442f8723
Build image provisioning date and time
Tue 26 May 2020 09:41:46 AM UTC
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by blackboxsw** [comment]
Opportunistic in Milestone 25. Not a blocker to release in Xenial, Bionic

**Comment by blackboxsw** [comment]
We migrated to self-hosted Jenkins due to QOS on Travis for opensource projects.
