### ISSUE TITLE
ua auto-attach doesn't work on AWS GovCloud

### ISSUE THREAD

**Issue by cmars** [canonical/ubuntu-advantage-client#1077]
UA client should auto-attach for cloud "aws-gov", same as if it was "aws". `POST /v1/clouds/aws/token` should work the same; contract service is able to verify the signed IID from these regions.

I think the issue is that UA client is getting "aws-gov" from cloud-init as the cloud name, and failing an exact match for "aws". Might want to do a prefix match instead so this isn't an issue for other special AWS regions in the future?

```
... - cli.py:(594) [ERROR]: Auto-attach image support is not available on aws-gov
See: https://ubuntu.com/advantage
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 576, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 616, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 89, in new_f
    return f(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 52, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 387, in action_auto_attach
    token = _get_contract_token_from_cloud_identity(cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 366, in _get_contract_token_from_cloud_identity
    cloud_type=cloud_type
uaclient.exceptions.NonAutoAttachImageError: Auto-attach image support is not available on aws-gov
See: https://ubuntu.com/advantage
```

**Comment by jaredledvina** [comment]
Folks here may be interested in following the AWS ARN format from https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arns-syntax which has another partition for the china region.

**Comment by mitechie** [comment]
Agree, we can work to make sure we don't just fix the gov issue but have it work in a more general sense. Given that this is image specific though, we should double check which of these we publish the pro images in just to be sure.

**Comment by rcj4747** [comment]
> Agree, we can work to make sure we don't just fix the gov issue but have it work in a more general sense. Given that this is image specific though, we should double check which of these we publish the pro images in just to be sure.

You should make it work in both while you're in there.  No reason to pay the development cost to do this twice and we'll need it.  I've run `cloud-id` in cn-nort-1 (Beijing) on a Xenial image (ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20200407 (ami-04efbaf491dc3e681)) and it returned `aws-china`

**Comment by mitechie** [comment]
> You should make it work in both while you're in there. No reason to pay the development cost to do this twice and we'll need it. 

Agree that we should make it work but we should also understand where it's expected and not expected to work as far as where we have images and don't. My understanding is that we have pro images in gov (recently) and do not in china so it's worth being aware for future engagements.

**Comment by kikoreis** [comment]
It's expected to work everywhere there are regions; not everything may be in place on day 1 on each region, but the expectation is that it's available wherever Ubuntu is available.
