### ISSUE TITLE
Need to press Enter twice during ua enable fips --beta

### ISSUE THREAD

**Issue by davecore82** [canonical/ubuntu-advantage-client#1083]
I'm testing the new ubuntu-advantage-tools version `25.0+202006031928-762~g70fe324~ubuntu18.04.1` on Ubuntu Pro 18.04 on AWS.

During the activation of FIPS with the new ua client with beta flag, the process hangs here:

```
ubuntu@ip-172-31-54-139:~$ sudo ua enable fips --beta
One moment, checking your subscription first
Installation of additional packages are required to make this system FIPS
compliant.
Are you sure? (y/N) y
Updating package lists
Installing FIPS packages
```

I looked at the logs in /var/log/apt and found that the process was waiting at the prompt:

```
A new version of /boot/grub/menu.lst is available, but the version
      installed currently has been locally modified.

      What would you like to do about menu.lst?

           install the package maintainer's version
           keep the local version currently installed
  [...]
```

So I pressed Enter twice in the original "ua enable fips --beta" session and the install proceeded and ended successfully:

```
FIPS enabled
A reboot is required to complete install
```

**Comment by blackboxsw** [comment]
I think this has been resolved by the commit https://github.com/canonical/ubuntu-advantage-client/commit/2b3c47f55820fe7339f2a7a3e0f97e4c55f7bd27
