### ISSUE TITLE
Add lxd vm-support for trusty. 

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1088]
stock kvm-type images for trusty are not available in simplestreams and will not be made available to us as trusty image builders have stopped at ESM-only support of trusty. 

We need a custom image creation in order to run behave integration tests on trusty If we wish to run vm-based tests on that release.

**Comment by blackboxsw** [comment]
Leaving this out of milestone 25 as we can manually cover the livepatch vm test for SRU into trusty until we get around to this

**Comment by orndorffgrant** [comment]
We no longer push new features to trusty so this is no longer needed.
