### ISSUE TITLE
ua status: rename --beta parameter to --all

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1091]
On review, @mitechie would like to ensure `ua status --all` lists all beta and production services.

We do not want to use --beta for ua status as it implies that the status output is in beta. 
It is appropriate to retain the `--beta` param used for both ua enable and disable.

**Comment by mitechie** [comment]
I think the idea is that there's more than beta/production services but also the idea that some services don't apply to your current instance. For instance, CC only works on 16.04.4 and no other point release. It's not that CC is in beta, but doesn't apply. So I think it's worth highlighting things that are applicable to your machine you're on, and "everything else".
