### ISSUE TITLE
FIPS: unhold any held fips packages.

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1109]
# BLOCKED on existing team discussion
Azure Ubuntu PRO FIPS preview image uses apt-mark hold to pin FIPS packages as part of the build process. On auto-attach uaclient will need to unhold those packages during FIPS enable.

**Comment by rcj4747** [comment]
You mention Azure's image, AWS will be the same.  Just an FYI.

**Comment by blackboxsw** [comment]
Thanks @rcj4747

> You mention Azure's image, AWS will be the same. Just an FYI.

Thanks @rcj4747

**Comment by blackboxsw** [comment]
Moving to milestone 26.0 as milestone 25.0 will likely be just full Xenial, Bionic Eoan and Focal release support. Fips will come in 26.0
