### ISSUE TITLE
ec2 and azure runs using pycloudlib need to cleanup any stale vms discovered from CI runs

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1143]
I'm seeing lots of stale instances left in our shared ec2 account from CI runs that were cancelled or not cleaned up properly. 
We have to think about a general cleanup mechanism that works properly for all CI runs, keeping in mind that we will have two or more concurrent travis jobs running (pro and non-pro).
things to clean:
   keys created
   instances
   images/snapshots

**Comment by lucasmoura** [comment]
Since we are now cleaning up the instances created during the travis run, I think this issue has been solved
