### ISSUE TITLE
apt update-notifier SRU to xenial,  bionic and focal

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1152]
Need to resolve the following bugs and xenial and bionic:
- [x] Xenial: No ESM* awareness of apt_check.py (diff from focal) https://paste.ubuntu.com/p/NykcGqYDhp
- [x] Bionic: No ESM* awareness in apt_check.py ( diff from focal) https://paste.ubuntu.com/p/CKbmNmhWyR/
- [x] Focal: No ESM Apps awareness (diff from focal) https://paste.ubuntu.com/p/XFrqnmc9pd/
- [x] "Showing esm update as installable when esm is disabled" ... https://bugs.launchpad.net/ubuntu/+source/update-notifier/+bug/1883315

**Comment by blackboxsw** [comment]
PRs put up for review:
[ ] [Xenial update-notifier](https://code.launchpad.net/~chad.smith/ubuntu/+source/update-notifier/+git/update-notifier/+merge/391841)
[ ] [Bionic update-notifier](https://code.launchpad.net/~chad.smith/ubuntu/+source/update-notifier/+git/update-notifier/+merge/391843)
[ ] [Focal update-notifier](https://code.launchpad.net/~chad.smith/ubuntu/+source/update-notifier/+git/update-notifier/+merge/391846)

**Comment by blackboxsw** [comment]
UPloads are queued Robie Basak reviewing on Monday, this is something that will need to be in before a public release to Xenial in milestone 27.0

**Comment by mitechie** [comment]
This seems to be in line with the spec on the apt messaging as well.

**Comment by blackboxsw** [comment]
I just set verification-done tag on https://bugs.launchpad.net/ubuntu/+source/unattended-upgrades/+bug/1915547 might need to tall to robiebasak again to see if this is settled

**Comment by blackboxsw** [comment]
This should be released into Xenial as version 3.168.14
