### ISSUE TITLE
on ua disable fips, should we remove all apt config  and leave installed packages?

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1168]
Questions to answer here:
- [ ] Currently we "do nothing" related to the FIPS apt configuraiton files on FIPS because "fips can't be disabled". Should we at least turn reomve apt config files so apt-cache policy shows no access to FIPS repos and ua status shows disabled?
- [x] For services which have installed pkgs by default, should disabling the service leave those packages installed (I think yes but wanted confirmation)   # resolved in 0371ce5a91f4683e8b82826405b385ea356b148c

**Comment by mitechie** [comment]
The second one is yes, if you've enabled something and gotten it running we don't keep you from having that but keep you from future updates. The product offering is the next update vs the one you already have. 

For the first one, I'm torn on this. FIPS is a kernel/package version that should be easily reversible. You should be able to install, reboot into FIPS, test something, and go back. That said, for safety sake, I'd suggest that we'd remove the report and access to future updates and helpfully output some messaging around switching the default kernel but not actively change anything.
