### ISSUE TITLE
'ua enable fips' should install the AWS or Azure optimized FIPS kernels by default

### ISSUE THREAD

**Issue by davecore82** [canonical/ubuntu-advantage-client#1176]
On both AWS and Azure, when using the latest UA client build from ppa:canonical-server/ua-client-daily, enabling FIPS installs the regular FIPS kernel (linux-fips) instead of the AWS or Azure optimized FIPS kernels (linux-aws-fips and linux-azure-fips).

Steps to reproduce:

-Launch Ubuntu Pro 18.04 instance in AWS or Azure

```
sudo add-apt-repository ppa:canonical-server/ua-client-daily --yes
sudo apt install ubuntu-advantage-tools ubuntu-advantage-pro --yes
sudo ua disable livepatch
sudo ua enable fips --beta
```
The regular FIPS kernel will be installed.

To install the Azure optimised FIPS kernel, the following workaround must be done:

`sudo apt install linux-azure-fips`

For AWS:

`sudo apt install linux-aws-fips`

**Comment by blackboxsw** [comment]
Commit 64c3860c3fdd5b4062bcc7a0358ca7363140e0d6 fixes this it is already built in ppa:canonical-server/ua-client-daily
 and will also be in the official ubuntu-advantage-tools v. 26.0 in ppa:ua-client/staging and ppa:ua-client/stable
