### ISSUE TITLE
Only enable features if images support them

### ISSUE THREAD

**Issue by rcj4747** [canonical/ubuntu-advantage-client#1180]
I am opening this issue in response to issue #1087.  There we had a situation where ubuntu-advantage-pro could be told by the store that FIPS was entitled and should be auto-enabled.  If an image was booted that contained code prior to the fix for that issue it would attempt to enable FIPS and fail in such a way that would break apt and the ability of the system to get updates.  We need to solve this specific issue of how we auto-enable FIPS given that there are images available which do not have the fix and how we would like to deal with this generically in the future.

The ua client is built into the image and packages are not updated at first boot before it is run.  So the version of the code in the image is what will be used for auto-attach.

If we do nothing we will break existing images when we change the backend to auto-enable FIPS for those products. 
Those earlier images when launched after FIPS is flagged as auto-enable will have apt broken such that automatic updates will not be applied and software installation will not work without manual intervention.

The UA client should only do what it knows how to do correctly given any possible direction from the backend but that argument ignores this existing issue and this class of issues in the future.

It may be necessary to send along the image build serial (as a proxy for the full package manifest) or at least the UA tools version to the backend with the auto-attach request so that the backend can conditionally enable features (or disable features that are known to break certain tool versions).

Alternatively the UA client could 'apt update' (images are stripped of apt cache during build), upgrade itself, and re-bootstrap.  The first boot speed impact of this may not be acceptable however.

**Comment by rcj4747** [comment]
@wiswaud FYI

**Comment by orndorffgrant** [comment]
We don't think this bug still applies. Pro images are updated with the latest UA for each release, and there are no current problems when enabling FIPS on Pro images. We also have official Pro FIPS images that auto-enable fips and are built fresh regularly, and are working well.

Please re-open this if we're missing something and this bug is still applicable.
