### ISSUE TITLE
ua help - fips updates description

### ISSUE THREAD

**Issue by lechsandecki** [canonical/ubuntu-advantage-client#1210]
can we change it to:
fips-updates
fips-updates installs fips modules including all security patches for those modules that have been provided since their certification date. You can find out more at https://ubuntu.com/security/certifications#fips

**Comment by blackboxsw** [comment]
@lechsandecki is it a request to change just the URL or do you want us to use lowercase for all FIPS and "FIPS Updates" occurrences in text?

Current text we have in tip is:
```root@behave-image-build--trusty1603205886859858:~# ua help fips-updates
Name:
fips-updates

Entitled:
yes

Status:
n/a

Help:
FIPS Updates installs FIPS updates modules including all security patches
for those modules that have been provided since their certification date.
You can find out more at ubuntu.com/security/fips
```

**Comment by lechsandecki** [comment]
thanks Chad
in fact there are 3 changes here:
1. fips-updates rather than FIPS Updates
2.fips modules instead of FIPS updates modules
3.and the link

**Comment by blackboxsw** [comment]
@lechsandecki while in there to change the cli help text shall I update the top-level help too?
```
 root@behave-image-build--trusty1603205886859858:~# ua --help
usage: ua [command] [flags]

Client to manage Ubuntu Advantage services on a machine.
....
 - esm-apps: UA Apps: Extended Security Maintenance
   (https://ubuntu.com/security/esm)
...
 - fips: NIST-certified FIPS modules (https://ubuntu.com/security/fips)
 - fips-updates: Uncertified security updates to FIPS modules
   (https://ubuntu.com/security/fips)
...
```

**Comment by blackboxsw** [comment]
Also the standard fips help message has the url https://ubuntu.com/security/fips should that also change to https://ubuntu.com/security/certifications#fips;

**Comment by lechsandecki** [comment]
yes please. I plan to work on the new fips page https://ubuntu.com/security/fips in Q4 2020. but it's not there yet. 
I will let you know once it's done. for not let's use https://ubuntu.com/security/certifications#fips please

**Comment by lechsandecki** [comment]
FYI I also updated the cis URL https://github.com/canonical/ubuntu-advantage-client/issues/1211
