### ISSUE TITLE
ua help - esm-infra description

### ISSUE THREAD

**Issue by lechsandecki** [canonical/ubuntu-advantage-client#1212]
esm-infra
esm-infra is enabled by default on entitled workloads. It provides access to a private ppa which includes available high and critical CVE fixes for Ubuntu LTS packages in the Ubuntu Main repository between the end of the standard Ubuntu LTS security maintenance and its end of life. You can find our more about the esm service at https://ubuntu.com/security/esm

**Comment by blackboxsw** [comment]
Since the previous text was the full product name:
UA Infra: Extended Security Maintenance  and now we have redacted that information in help text, is the intent to drop that UA Infra vs UA Apps in general throughout documentation?

Currently top-level `ua  help` show the following for esm-infra and esm-apps:
```
 - esm-apps: UA Apps: Extended Security Maintenance
   (https://ubuntu.com/security/esm)
 - esm-infra: UA Infra: Extended Security Maintenance
   (https://ubuntu.com/security/esm)
```


Also MOTD messaging will have messages like the following:
```
UA Infrastructure Extended Security Maintenance (ESM) is enabled.
5  of these updates is provided through UA Infrastructure ESM.
````


And when apt update is run on the commandline, this type of message:
```
5 of the updates is from UA Infrastructure ESM.
3 of the updates is from UA Apps ESM.
```


@lechsandecki @mitechie To make sure our product marketing is consistent in these user-facing messages, how should we plan to unify these messages?

**Comment by lechsandecki** [comment]
I'd stick to UA Apps, UA Infra
both ESM or Extended Security Maintenance (depending on context) are fine
so I'd suggest

` - esm-apps: UA Apps: Extended Security Maintenance (ESM)
   (https://ubuntu.com/security/esm)
 - esm-infra: UA Infra: Extended Security Maintenance (ESM)
   (https://ubuntu.com/security/esm)`


`UA Infra: Extended Security Maintenance (ESM) is enabled.
5  of these updates is provided through UA Infra: ESM.`

and

`5 of the updates is from UA Infra: ESM.
3 of the updates is from UA Apps: ESM.`

wdyt?

**Comment by blackboxsw** [comment]
Thanks @lechsandecki, So in initial `ua help` info we'll leave the UA Apps: Extended Sucurity Maintenace (ESM) text.

The question I posed here was also to suggest that our ua help esm-infra also use that same text somewhere as it is the detailed help for the service.

> I'd stick to UA Apps, UA Infra
> both ESM or Extended Security Maintenance (depending on context) are fine
> so I'd suggest
> 
> > * esm-apps: UA Apps: Extended Security Maintenance (ESM)
> >   (https://ubuntu.com/security/esm)
> > * esm-infra: UA Infra: Extended Security Maintenance (ESM)
> >   (https://ubuntu.com/security/esm)
> 
> > UA Infra: Extended Security Maintenance (ESM) is enabled.
> > 5  of these updates is provided through UA Infra: ESM.
> 
+1. We can make sure update-notifier and release to groovy and SRU back to xenial for proper MOTD update messaging

> and
> 
> > 5 of the updates is from UA Infra: ESM.
> > 3 of the updates is from UA Apps: ESM.
> 
> wdyt?
@lechsandecki This works for me in the APT cli context (which we can change in ua-tools deb package in this repo).

**Comment by lechsandecki** [comment]
esm-infra
esm-infra provides access to a private ppa which includes available high and critical CVE fixes for Ubuntu LTS packages in the Ubuntu Main repository between the end of the standard Ubuntu LTS security maintenance and its end of life. It is enabled by default with Extended Security Maintenance (ESM) for UA Apps and UA Infra. You can find our more about the esm service at https://ubuntu.com/security/esm
