### ISSUE TITLE
rename the proposed ua client ppa

### ISSUE THREAD

**Issue by lechsandecki** [canonical/ubuntu-advantage-client#1215]
could you rename the ppa [1] so that it won't be confused with the proposed pocket of Xenial and Bionic, please?

https://launchpad.net/~ua-client/+archive/ubuntu/proposed

**Comment by blackboxsw** [comment]
https://launchpad.net/~ua-client/+archive/ubuntu/staging has the 25.0 beta2 deb packages as of 10/27. We expect to have beta3 out tomorrow and the release 25.0 this week.
