### ISSUE TITLE
26.0 UA-client upgrade support from old Azure Ubuntu PRO FIPs images which contain a version of ua-tools with FIPS gpg key

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1224]
A feature-request for us to decide on:
  Some Azure PRO FIPS images are still launchable in the Azure portal with a ua-tools/pro deb package that did not contain a static GPG  keyring authorized to the FIPS PPA.
  
  What is the upgrade support plan for getting those vms images updated to uaclient 26.0 with fips support?

If FIPS auto-enabled by contract server, fips on old UA Client will hit GPG key error issues if fips gets enabled before upgrade to v 26.0

**Comment by mitechie** [comment]
We'll document this but the answer is to upgrade the client or use a newer CPC image.

**Comment by blackboxsw** [comment]
The only contract which auto-enables FIPS is Ubuntu PRO FIPS offering which has the right GPG keys installed. As CPC team provides newer PRO FIPS images, the right ubuntu-fips metapkg and GPG key related to the fips PPA will be properly setup by uaclient 26.0 or later.
