### ISSUE TITLE
UA Client auto-attach needs to be aware of potential timing conflicts when processing user-data for datasources detected at init-network timeframe

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1246]
auto-attach systemd unit is currently triggered the moment /run/cloud/intance-data.json is written (at cloud-init's python datasource detection occurs), for datasources detected in init network stage (instead of init-local) this represents a potential race condition with auto-attach if cloud-init is also processing user-data which installs deb packages or manipulates apt config.

**Comment by renanrodrigo** [comment]
Tracking in SC-835

**Comment by orndorffgrant** [comment]
There should no longer be race conditions with the init network stage because auto attach now runs:
```
After=cloud-config.target
```
and
```
Before=cloud-config.service
```
