### ISSUE TITLE
Invalid command: "attach"?

### ISSUE THREAD

**Issue by theheatDK** [canonical/ubuntu-advantage-client#1250]
Hi,
In the project, README is stated that you can attach a machine to an Ubuntu Advantage contract by:
`sudo ua attach <contractToken>`

When I try that I get this error:
```
sudo ua attach MYTOKEN
Invalid command: "attach"
```

The "ua help" command also shows that there is not attach command.

What am I missing? :-)

```
sudo ua version
17
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

```

Regards Peter

**Comment by mitechie** [comment]
17 is an older version of the client that really doesn't support
18.04. To use the ua client on bionic, v25, please use the PPA here:

https://launchpad.net/~ua-client/+archive/ubuntu/staging
(and soon to move to stable here)
https://launchpad.net/~ua-client/+archive/ubuntu/stable

**Comment by theheatDK** [comment]
Thanks @mitechie :-)
You are a lifesaver. It now works.
It took me 6 hours to get to this point :-(
I am very surprised that it is not mentioned anywhere that the version of the tool that you get if you have an up to date server is useless. 
I am getting a bit nervous. Is UA a product that is widely used?
What my customer really need is CIS hardening and an on-premise off-line patch solution.
CIS is not available for 20.04 yet and I am after 6 hours still working on getting access to CIS for 18.04.
Am I leading them down the wrong path? :-)
Regards Peter

**Comment by theheatDK** [comment]
If another non-Ubuntu person ends up here. This is what I did:
```
sudo apt update
sudo apt remove ubuntu-advantage-tools
sudo add-apt-repository ppa:ua-client/staging
sudo apt-get update
sudo apt install ubuntu-advantage-tools
sudo ua version
```

**Comment by mitechie** [comment]
The UA client is used heavily on Trusty and Focal currently. We're working
to enable xenial and bionic support outside of Ubuntu pro online images.

I know that the CIS functionality is there but needs a non-free
subscription to be entitled to that. I've not tested it personally and will
need to see about getting a better subscription to test it out.

If you have a valid subscription after attaching you should be able to try:
ua enable cis-audit --beta
on a bionic system.

**Comment by theheatDK** [comment]
Thanks Rick
