### ISSUE TITLE
ua status to report reboot required

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1251]
When a reboot is required to complete a config change for a given ubuntu advantage service, ua status shall report a reboot-required message from ua status. 

Please adapt this issue description with the suggested direction for messaging about reboots required.

UA client could provide messaging about the following scenarios:
  - reboot required to complete <service_name> enable  # livepatch enable across LTS upgrade
  - reboot required to complete <service_name> disable  # FIPS disable case
  - general system reboot required                                    #  some out-of-band deb install created /var/run/reboot-required

This issue represents a usability request to define messaging from `ua status` tabular  format to handle these cases.

Options we currently have:
 1. add new reboot-required messaging somewhere in `ua status` output, the messaging will be tailored to the specific reboot case 
 2. Could use descriptionOverride options to present the affected service STATUS as "pending" and DESCRIPTION as "reboot-required to complete <operation>"

Current UA status output for reference
root@dev-b:~# ua status --all
```bash
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        yes       n/a       Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-apps      no        —         UA Apps: Extended Security Maintenance
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
fips          yes       enabled   NIST-certified FIPS modules
fips-updates  yes       disabled  Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service

Enable services with: ua enable <service>

     Account: chad.smith@canonical.com
Subscription: chad.smith@canonical.com
```

**Comment by blackboxsw** [comment]
Proposed examples for discussion:

* use case 1: attached system with no active UA operations in progress
```bash

SERVICE       ENTITLED  STATUS    DESCRIPTION
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
livepatch     yes       n/a       Canonical Livepatch service

Enable services with: ua enable <service>

      Account: chad.smith@canonical.com
 Subscription: chad.smith@canonical.com
       Status: inactive
StatusDetails: No Ubuntu Advantage operations are running
```

* use case 2: system's reboot-required flag indicates system reboot needed
```bash
...
       Status: reboot-required
StatusDetails: A reboot is required due to system reboot-required flag
```
* use case 3: UA client config change operations still pending at next boot
```bash
...
        Status: reboot-required
 StatusDetails: A reboot is required to enable livepatch (or fips etc.)
````

**Comment by mitechie** [comment]
I had started to poke at your pastebin yesterday Chad. I think we should have some sort of available section like so:

https://pastebin.canonical.com/p/bzZ8z7PF5c/

This gives us a place to put information that might come up. We already know we have situations where something is enabled but not working properly, or some other next steps. Let's try this out to start with and we'll get feedback and update it from there. 

Thanks!
