### ISSUE TITLE
Can't Enable CIS Automated Hardening Tools on Ubuntu Pro 18.04 via AWS Marketplace

### ISSUE THREAD

**Issue by sudo-create** [canonical/ubuntu-advantage-client#1277]
I am trying to enable CIS Automated Hardening tools on Ubuntu 18.04 using a Pro subscription . The configuration steps are described here by Canonical: https://www.youtube.com/watch?v=wyEX0eyoK88

Specifically, I am trying to install `usg-cisbenchmark`

I am subscribed to the Ubuntu Pro 18.04 (20201014) marketplace AMI: https://aws.amazon.com/marketplace/pp/Amazon-Web-Services-Ubuntu-Pro-1804-LTS/B0821T9RL2

This guide here (https://security-certs.docs.ubuntu.com/en/cis-18-16) seems to rely on having a direct relationship with Canonical rather than purchasing through the AWS marketplace.

1. Determine your Launchpad username by going to launchpad.net/~
2. Request access to the CIS Benchmark tool's PPA by logging in to support.canonical.com and following the instructions on the Contact Us tab to create a new case. Please include your Launchpad username in the support case.
3. It may take up to 48 hours, but you will be notified once your access has been granted.
4. Click this link to view your Private PPA subscriptions.
5. Under Archive locate the "Security Benchmarks" (ppa:ubuntu-advantage/security-benchmarks) line and click "View" to the right.
6. Locate the line starting with deb `https://your-launchpad-id:PPA-password@`, where `your-launchpad-id:PPA-password` represent your personal Launchpad username and the encoded password created for this PPA.
7. Select and copy the portion comprising of `your-launchpad-id:PPA-password`

Both the video and the AMI indicates the image includes tools for automated CIS hardening. Are there different instructions to enable and use the tooling? I apologize for my confusion here, there may be a simple answer to this.

**Comment by mitechie** [comment]
This is in flux in that we are working to include the CIS access into the ua client for bionic and focal. That said, it's not yet there and expected in the first quarter of next year. 

Until that occurs access is handled manually by getting credentials to the secure PPA. For now, you'll have to go through the steps in the guide you noted.

**Comment by sudo-create** [comment]
I really appreciate the guidance, this makes sense. I certainly don't mind doing that. I was able to create an Ubuntu One account and log into Launchpad in Step 1. In Step 2 it states I need to open a support.cononical.com case. When I attempt to navigate there I am met with "I'm sorry but for some reason we weren't able to let you in to the support portal via Ubuntu Single Sign On." I don't have a subscription with Canonical because I am subscribing through the AWS marketplace. How does one go about opening a support case in this instance when the paid subscription is through AWS? Seems like I am stuck at Step 2 until I can get around this. I have 20+ servers I am working to get this deployed on where I have this active subscription with more on the way. Thanks again for the guidance.

**Comment by mitechie** [comment]
Thanks for bearing with me. I asked internally about someone in your situation and got these instruction notes back. If you do those steps let me know and I can also ping someone internally to make sure they pick it up and follow up as next steps. 

---
Please have them fill out the bitstream form to ask for access to the CIS tools: https://forms.canonical.com/bitstream/

They will have to provide 2 pieces of information:
1. An output from the command "ua status" so that we can verify their entitlement to the CIS tool.
2. Their Launchpad username. They will have to create an account on UbuntuOne first (https://login.ubuntu.com/). Once that is done, they can go to https://launchpad.net/~ to get their user id.

With that information the STS support team can provision their CIS access almost immediately.

**Comment by sudo-create** [comment]
Thank you for your help. 

I filled out the bitstream form as requested with an output from `ua status` and I also included my launchpad id/username.

Now I am just waiting for the STS support team to provision CIS access.

**Comment by sudo-create** [comment]
I just wanted to follow up going through the bitstream form resolved my issue. 

Thank you for your help.
