### ISSUE TITLE
CIS requires apt_noninteractive as true to be enabled by uaclient

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-advantage-client#1287]
When trying to enable cis with `apt_noninteractive` as `False`  we get:

```
ProcessExecutionError("Failed running command 'apt-get install --assume-yes usg-cisbenchmark usg-common' [exit(100)]. Message: debconf: delaying package configuration, since apt-utils is not installed\nE: Sub-process /usr/bin/dpkg returned an error code (2)\n",)
```

Even installing the `apt-utils`  package does not solve the issue.

Also, running the `apt-get install` command does not trigger any interactive prompt.

**Comment by renanrodrigo** [comment]
`apt_noninteractive` is set to true for CIS/USG
