### ISSUE TITLE
parallel jenkins jobs on the same worker cannot use BUILD_PR=1 due to collisions writing tarfiles on the /tmp directory

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1292]
With multiple jenkins jobs running behave on the same physical machine, there are intermittent errors when BUILD_PR=1 is specified because all integration runs attempt to simultaneously create /tmp/pr_source.tgz  before building deb packages in a vm. They also simultaneously try to save output debs to the same output_deb_dir causing write collisions or overrite race conditions when multiple builders are working together.

Fix datadir paths to be job-specific.

**Comment by TheRealFalcon** [comment]
If the tests creating the `/tmp` tarball are using the `tempfile` module, ideally this will only setting something like `TMPDIR=$WORKSPACE/$BUILD_TAG` in each of the parallel tasks
