### ISSUE TITLE
fips enable warning isn't helpful

### ISSUE THREAD

**Issue by mitechie** [canonical/ubuntu-advantage-client#1313]
sudo ua enable fips --beta
    One moment, checking your subscription first
    Installation of additional packages are required to make this system FIPS
    compliant.
    Are you sure? (y/N) y

The "installation of additional packages" seems kind of unhelpful. I think there's a more clear warning of the impact of fips we can highlight here.

**Comment by renanrodrigo** [comment]
@lucasmoura can we re-evaluate this with the new scary stuff?

**Comment by lucasmoura** [comment]
Yes, I think we can close this one after the prompt update
