### ISSUE TITLE
GCP: `ua enable fips` should not install linux-fips kernel

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1317]
GCP images come with a GCP-specific kernel `linux-gcp` installed. `ua enable fips` installs `linux-fips` which is not a gcp-specific kernel. Is this a regression of behavior for GCP environments?

**Comment by mitechie** [comment]
We don't have a fips certified google kernel so this should not be available to enable for now. Maybe with --beta we can use the default as a testing scenario, but really it's not supported.

**Comment by mitechie** [comment]
We should treat it like unsupported combo on azure/aws and block by default with a --beta override where someone is ok and accepts that.
