### ISSUE TITLE
BDD: add mechanism by which integration tests can respond to input prompts

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1327]
In #1315 we added a config `feature:: block_disable_on_enable: true` due to a shortfall in our ability to instrument stdin input within integration tests.   Ultimately this config parameter shouldn't really be surfaced to the end-user.

Let's define a mechanism by which our integration tests can provide input "answers" to various CLI input prompts that are presented by UAClient.

**Comment by orndorffgrant** [comment]
Closing because this is done.
