### ISSUE TITLE
Security API: pocket and pocket_source fields of CVE package status do not represent esm-apps or esm-infra pockets

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1376]
CVE responses from the security API do not report pockets that are indicative of esm-apps or esm-infra. UA client currently relies on checking "esm" in description to determine if a pkg is resident in an "esm-infra" pocket. This is waiting on Security team to fill in appropriate pocket details in the Security API db.

```json
        {                                                                       
          "component": null,                                                    
          "description": "2:4.3.11+dfsg-0ubuntu0.14.04.20+esm9",                
          "pocket": null,                                                       
          "release_codename": "trusty",                                         
          "status": "released"                                                  
        }, 
```

**Comment by orndorffgrant** [comment]
@blackboxsw We're closing this as we believe it is already fixed. Please re-open if we're mistaken.
