### ISSUE TITLE
fix: add mechanism to switch between staging and prod security url

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-advantage-client#1394]
To use the security api on our code, we go through the following steps:
     
1. We define on the defaults module:
https://github.com/canonical/ubuntu-advantage-client/blob/master/uaclient/defaults.py#L17

2. In the serviceclient module we read that url directly to perform a request:
https://github.com/canonical/ubuntu-advantage-client/blob/master/uaclient/serviceclient.py#L56

This means we don't have a supported way to switch between the staging and prod security urls at the moment. We should have a config feature that allows to switch those APIs

**Comment by blackboxsw** [comment]
This switch should be handled by either uaclient.conf changes setting security_url : some.staging.com   or running commands with `UA_SECURITY_URL=https://some.staging.com ua fix USN-blah`.


So I don't think this is an issue here's my local test proving override by env var
```bash
UA_SECURITY_URL=http://bogus PYTHONPATH=. python3 -m uaclient.cli fix USN-4539-1
Failed to connect to authentication server
Check your Internet connection and try again
```

Please re-open if this is still an issue.

Also somewhat related to config overrides via environment variables I just filed a separate issue so we could also provide feature toggles via env var.
https://github.com/canonical/ubuntu-advantage-client/issues/1395
