### ISSUE TITLE
When running ua fix do we really want to print all of the apt commands to the user

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-advantage-client#1400]
On ua fix, we intend to give users visibility of what commands we are performing on uaclient backend. However, a lot of commands are run during an `attach` operation for example. Here is the filtered output of the commands we run when running `attach` on a bionic vm:

```
apt-cache policy
apt-cache policy
apt-cache policy
apt-cache policy
/usr/lib/apt/apt-helper download-file https://bearer:TOKEN@esm.ubuntu.com/infra/ubuntu/pool/ /tmp/tmps0e0r6vr/apt-helper-output
apt-cache policy
apt-config shell key Dir::Etc::netrcparts/
Updating package lists
apt-get update
ESM Infra enabled
apt-cache policy
apt-cache policy
systemd-detect-virt --quiet --container
apt-cache policy
apt-cache policy
apt-cache policy
apt-cache policy
apt-cache policy
apt-cache policy
apt-cache policy
dpkg-query -W --showformat=${Package}\n
/usr/bin/snap wait system seed.loaded
Installing canonical-livepatch snap
/usr/bin/snap install canonical-livepatch
/snap/bin/canonical-livepatch config remote-server=https://livepatch.canonical.com
/snap/bin/canonical-livepatch status
/snap/bin/canonical-livepatch status
/snap/bin/canonical-livepatch status
```

If even we filter the `apt-cache policy` commands out, we can still see that a lot of these commands seem to not be useful to the user. We also have other issues here. For example, when enabling ESM, we create some apt configuration files. Should we expose that process to the user as well ?

The main question here is, what is the type of commands that we really want to expose to the user ?

**Comment by mitechie** [comment]
No, this is just intended for the root command. Where the user could be running it themselves (in this case ua attach) and then the output we'd normally show for a user running `ua attach`. 

When we update the package we run a single `apt upgrade <packagename>` and that should be run/shown as if the user ran it.

**Comment by lucasmoura** [comment]
Just to confirm, supposing that the user is unattached to the machine. When we perform an attach operation during `ua fix`, we want to print:

* The attach commands itself
* apt update
* Any apt upgrade commands that were used to update the packages

**Comment by mitechie** [comment]
Yes, and possibly a `ua enable` command if necessary. e.g. if they don't currently have esm for apps enabled but would need it to get access to the fix and they're entitled to it then we'd show them the `ua enable esm-apps` and that output, then followed by a `apt update && apt upgrade <x>`

**Comment by mitechie** [comment]
Fundamentally ua fix is meant to walk the user through the steps they could in theory do themselves at the highest level possible (ua and apt commands they could run)

**Comment by lucasmoura** [comment]
Got it. It makes sense now. Thanks for the context @mitechie
