### ISSUE TITLE
console: define workflow from ua fix when ua client opts to create a subscription

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1413]
On the console, the client tells a customer to:
```bash
Opening https://ubuntu.com/advantage/subscribe …
```

Shall the client block awaiting an update from a TBD contract endpoint that a new contract has been created to finish that attach without needing a token?
OR does the subscription endpoint return a token or key that the customer can then enter on the CLI client?

**Comment by lechsandecki** [comment]
seems that @mitechie already replied to this in the spec

**Comment by renanrodrigo** [comment]
As it didn't come out of the spec, we don't foresee this implemented.
I will close this issue - please feel free to reopen if this feature is really desired so we can spec it out based on the current state of the project.
