### ISSUE TITLE
prioritize update and prompts for -updates -security packages prior to token attach

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1438]
1. Upfront say affected packages that aren't resolvable, an whether fix is in ESM* with token attach
    Unfixable
    Standard updates
     UA update
2. Prompt "do you want to upgrade these package (Y/n)"
3. Standard -updates first with apt prompt
4. If unattached, prompt for tokens
5. New message for resolved as much as we can (if unable to fix needs-triage type packages)

**Comment by mitechie** [comment]
I don't get your output Lucas. 2/2 should begin walking through attaching the token and enabling the service vs saying "not installed because of things..." shouldn't it?

**Comment by lucasmoura** [comment]
Oh sorry, I just realized that I butchered that comment :facepalm: Let me update with the correct message

**Comment by lucasmoura** [comment]
@mitechie @blackboxsw I have updated the comment to something that makes sense now

**Comment by mitechie** [comment]
```
2 affected packages are installed: curl, slsrc
(1/2) curl:
A fix is available in Ubuntu standard updates.
The update is not yet installed.

I don't think we need this line above at all in the non-esm cases. It's only there in the spec to help indicate that the package isn't/cannot be installed until the subscription is at play. 


Installing packages from standard updates: curl
{ apt update && apt install --only-upgrade -y curl }
(2/2) slsrc:
A fix is available in UA Infra.
The update is not yet installed.

Again, in this case, an already attached machine, I don't think we need to say it's not already installed. In fact, if was already installed we wouldn't show it as an affected package on the system correct? 


Installing packages from standard updates: curl
{ apt update && apt install --only-upgrade -y curl }
Installing packages that requires a ubuntu-advantage-tools subscription: slsrc
The update is not installed because this system is not attached to a subscription.
```

And here I see that I misunderstood where it was going. I think this is too much noise at this point. We're knowingly failing at installing a package in order to get to the error that this needs a subscription?

**Comment by lucasmoura** [comment]
```
Again, in this case, an already attached machine, I don't think we need to say it's not already installed. In fact, if was already installed we wouldn't show it as an affected package on the system correct?
```

Not entirely, we would still list that package during `ua fix`, but instead of `The update is not yet installed.` we would have `The update is already installed.`

```
We're knowingly failing at installing a package in order to get to the error that this needs a subscription?
```

No, currently we have a logic to determine if a package needs a uaclient subscription or not. Therefore we have two bucket of packages: standard updates packages and ua packages. Since we know that beforehand, we can ask the user for a subscription before attempting to install it.

**Comment by mitechie** [comment]
Ok, my feedback is that after we do the install of the first package that was in main we go straight into the spec'd output for the esm related package

```
(1/1) aftpd:
A fix is available in UA Infra: ESM.
The update is not installed because this system is not attached to a subscription.
Choose: [S]ubscribe at ubuntu.com [A]ttach your existing token [C]ancel
```

**Comment by mitechie** [comment]
I would expect we'd combine them like the other scenario. 

```4 affected packages are installed: pkg1, pkg2, pkg3, pkg4
(1/4, 2/4) pkg1, pkg2:
A fix is available in Ubuntu standard updates.
{ apt update && apt install --only-upgrade -y pkg1 pkg2 }
(3/4, 4/4) pkg3, pkg4:
A fix is available in UA Infra.
The update is not installed because this system is not attached to a subscription.
Choose: [S]ubscribe at ubuntu.com [A]ttach your existing token [C]ancel
<Attach Token>
{ apt update && apt install --only-upgrade -y pkg3 pkg4 }
```

Note that we don't need the extra "The update is not yet installed." on both situations.

**Comment by lucasmoura** [comment]
Fair enough, I think this solution makes sense. Thanks for the help @mitechie

**Comment by lucasmoura** [comment]
@mitechie Just another question on this issue, suppose we have two packages `pkg1` and `pkg2` . The fix for the first is found on `ESM Infra` while the second one is on `ESM Apps`. Suppose that the user is also not attached to ua subscription. In the fix command output will be something like this for this situation:

```
(1/2) pkg1:
A fix is available in UA Infra.
The update is not installed because this system is not attached to a subscription.
Choose: [S]ubscribe at ubuntu.com [A]ttach your existing token [C]ancel
<Attach Token>
{ apt update && apt install --only-upgrade -y pkg1 }
(2/2) pkg2:
A fix is available in UA Apps.
{ apt update && apt install --only-upgrade -y pkg2 }
```

But what should we do if the user do not attach for `pkg1`. Should we still show the status of `pkg2` or should we just abort and say that the issue cannot be solved ?

**Comment by mitechie** [comment]
They'll need to attach for both so I think we abort and say it cannot be solved. We have another issue/note that the output for the X at the end of the output should clarify the packages that still need updating to be clear in the cases where multiple package updates are needed. 

https://github.com/canonical/ubuntu-advantage-client/issues/1448
