### ISSUE TITLE
ua enable fips --assume-yes should work in a container environment

### ISSUE THREAD

**Issue by mitechie** [canonical/ubuntu-advantage-client#1441]
Cannot install FIPS on a container
Error: error building at STEP "RUN ua enable --assume-yes fips": error while running runtime: exit status 1

While we cannot change the kernel a FIPS container still needs the right other packages (openssl, openssh, etc) to work properly. 

Can we detect the container path well enough to "do the right thing"?

**Comment by nmav** [comment]
This blocks building containers to run on a FIPS-enabled system. This is a very important use case.

**Comment by mitechie** [comment]
We've hit a roadblock in that the ua client relies on deploying the FIPS metapackage that the security team provides. However, that is based on and installs the kernel which is not appropriate for a container environment. I'll sync with the security team on having a container environment a supported and valid product that the UA client can enable and install.

**Comment by davecore82** [comment]
Another way to make this work would be to allow the users to just enable the FIPS/FIPS Updates repos and not install any packages.  Then the user could install the packages they want (ie. openssl fips) without pulling in the kernel.

**Comment by orndorffgrant** [comment]
This was fixed and will be released in version 27.7
