### ISSUE TITLE
DevFeature: ability to fake any serviceclient API response

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1489]
When testing potential impact of an upgrade in backend API service. It is helpful to be able to fake API responses in the service client.

Provide a mechanism, config of environment variable by which any number of API responses can be "faked" for testing purposes.

**Comment by lucasmoura** [comment]
We have successfully implemented that feature:
https://github.com/canonical/ubuntu-advantage-client/commit/f3dbfed1f1f6560bdc27157b6a14043d297267a5
