### ISSUE TITLE
trusty: no upstart reboot-cmds script

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1494]
If we want to retain trusty support, we need an upstart module for ua-reboot-cmds.conf in upstart that needs inclusion in the trusty package.

**Comment by orndorffgrant** [comment]
@blackboxsw  @lucasmoura We're starting to remove trusty support, so should this issue be closed?

**Comment by lucasmoura** [comment]
Yes, I think we can close it. Thanks @orndorffgrant
