### ISSUE TITLE
apt upgrade/dist-upgrade: include esm-apps esm-infra security package counts prior to dist-upgrade 

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1537]
when running `apt upgrade or apt dist-upgrade` on an esm enabled system: report the security package count upgrade being applied for esm-apps and/or esm-infra

Current messaging 
```bash
73 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
```

Proposed messaging
```bash
4 upgraded, including 4 esm-apps security updates, 0 newly installed, 1 to remove an 0 not upgraded
```

**Comment by blackboxsw** [comment]
This likely will require APT pkg SRU.

**Comment by orndorffgrant** [comment]
@blackboxsw This is done right?
