### ISSUE TITLE
apt upgrade/dist-upgrade: include unapplied esm-apps or esm-infra security package counts

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1538]
On Ubuntu releases currently in active ESM, report available ESM Apps and/or ESM Infra package counts if a UA subscription were added and specific package names of affected pkgs.

proposed text
```bash
The following packages could receive security updates with ESM Apps service enabled:
  redis slurm-llnl
2 esm-apps security updates NOT APPLIED
```

**Comment by orndorffgrant** [comment]
@blackboxsw This is done right?
