### ISSUE TITLE
status: ua status fails if run proir to cloud-init detecting the platform type

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1541]
If cloud-init has not yet detected the datasource, it hasn't yet persisted instance-data,json.  This results in an error from `cloud-id` :

ERROR: File not found '/run/cloud-init/instance-data.json'. Provide a path to instance data json file using --instance-data

This in turn prevents `ua status` from outputting any useful information.
```bash
root@sbqt:~# ua status
Unexpected error(s) occurred.
For more details, see the log: /var/log/ubuntu-advantage.log
To file a bug run: ubuntu-bug ubuntu-advantage-tools
```

**Comment by renanrodrigo** [comment]
I like how GH points to a new commit fixing the issue after each ammend  \\\_("/)\_/
:eyes:
