### ISSUE TITLE
integration test pro: infrequent timing error on launched PRO test instance

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1543]
I've only seen this once. Something in integration tests image snapshot for PRO images hit a collision with a 2nd instance of ua-auto-attach running from the ua-auto-attach.service itself resuting in a failed ua-auto-attach. This should never happen on production services, but maybe we need a retry loop for auto-attach if it hits a lock collision.

● ua-auto-attach.service - Ubuntu Advantage auto attach
   Loaded: loaded (/lib/systemd/system/ua-auto-attach.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2021-04-12 15:29:40 UTC; 56s ago
  Process: 2620 ExecStart=/usr/bin/ua auto-attach (code=exited, status=1/FAILURE)
 Main PID: 2620 (code=exited, status=1/FAILURE)

Apr 12 15:29:39 ip-192-168-8-233 systemd[1]: Starting Ubuntu Advantage auto attach...
Apr 12 15:29:40 ip-192-168-8-233 ua[2620]: Unable to perform: ua auto-attach.
Apr 12 15:29:40 ip-192-168-8-233 ua[2620]: Operation in progress: ua auto-attach (pid:1308)
Apr 12 15:29:40 ip-192-168-8-233 systemd[1]: ua-auto-attach.service: Main process exited, code=exited, status=1/FAILURE
Apr 12 15:29:40 ip-192-168-8-233 systemd[1]: ua-auto-attach.service: Failed with result 'exit-code'.
Apr 12 15:29:40 ip-192-168-8-233 systemd[1]: Failed to start Ubuntu Advantage auto attach.

**Comment by orndorffgrant** [comment]
Marking closed because this hasn't come up again in tests or production. We will re-open if we start encountering it more.
