### ISSUE TITLE
xenial motd message links should point to /16-04 vs /advantage

### ISSUE THREAD

**Issue by mitechie** [canonical/ubuntu-advantage-client#1584]
Per the title

**Comment by blackboxsw** [comment]
Question 1: Do we want to plan for ubuntu.com/18-04 once bionic goes ESM?

Question 2: Here are the list of advantage MOTD url messages we emit. I'm suspecting we don't want all of them to point to ubuntu.com/16.04 (for example contract expiry messages) But please confirm what messages should be 16-04 on ESM releases 

Do we want ubuntu.com/16-04 instead of ubuntu.com/advantage on #3-#5 which are generally for APT messaging?

Assuming YES ubuntu.com/16-04 instead  of ubuntu.com/advantage:
1.
```MESSAGE_ANNOUNCE_ESM = """\                                                     
 * Introducing Extended Security Maintenance for Applications.                  
   Receive updates to over 30,000 software packages with your                   
   Ubuntu Advantage subscription. Free for personal use.                        
                                                                                
     {URL/16-04}
```
2.
```
*The following packages could receive security updates with {title} service enabled:
  {pkg_names}                                                                   
Learn more about {title} service at {URL/16.04}  
```

Questions : should attached machine expiry messages continue to point to ubuntu.com/advantage dashboard:

3.
 ```CAUTION: Your {title} service will expire in {remaining_days} days.             
Renew UA subscription at {URL/advantage}? to ensure                                        
continued security coverage for your applications.
```
4.
 ```CAUTION: Your {title} service expired on {expired_date}.                        
                                                                                
Renew UA subscription at {URL/advantage?} to ensure                                        
continued security coverage for your applications.                              
Your grace period will expire in {remaining_days} days.
```

5.
```*Your {title} subscription has EXPIRED*                                         
Enabling {title} service would provide security updates for following packages: 
  {pkg_names}                                                                   
{pkg_num} {name} security updates NOT APPLIED. Renew your UA services at        
{URL/advantage}?
```

**Comment by mitechie** [comment]
Adding @lechsandecki for feedback on the questions

**Comment by lechsandecki** [comment]
hi!

q1. YES, 18.04 should have its own page - by when it goes ESM (perhaps sooner)
q2. the goal is to walk the journey of "why is ESM important and you might need it", (especially in the 16.04 ESM context) rather than push them straight to the /advantage shop. 

Before we brainstorm that, let me ask you something @blackboxsw :
- can we use the /16-04 URL for 16.04 users only, or does it have to be generic?

**Comment by blackboxsw** [comment]
@lechsandecki 

> hi!
> 
> q1. YES, 18.04 should have its own page - by when it goes ESM (perhaps sooner)
> q2. the goal is to walk the journey of "why is ESM important and you might need it", (especially in the 16.04 ESM context) rather than push them straight to the /advantage shop.
> 
> Before we brainstorm that, let me ask you something @blackboxsw :
> 
> * can we use the /16-04 URL for 16.04 users only, or does it have to be generic?

@lechsandecki We plan to add  add the u.com/16-04 URL for 16.04 users only. I was only ondering if in attached machine with expiring contract what your thoughts were on using the generic dashboard (u.com/advantage) vs. specific u.com/16-04 URL in those *expired or near-expired* cases.    These URLs will be the generic dashboard on all non-16.04 Releases.

**Comment by lechsandecki** [comment]
ok, thanks @blackboxsw 

in that case, I think that we should update the URL in the following 16.04 scenarios (please note that I excluded all UA Apps: ESM cases)

[1] APT
*The following packages could receive security updates with UA Infra: ESM service enabled:
   libkrad0
Learn more about UA Apps: ESM service **for Ubuntu 16.04** at https://ubuntu.com/**16-04**

[2] MOTD
1 additional security updates can be applied with UA Infra: ESM
Learn more about enabling UA Apps: ESM service **for Ubuntu 16.04** at https://ubuntu.com/**16-04**

I think that only those 2 scenarios are covering the initial discovery. Beyond that, I'd point people directly to /advantage. I would consider adding /esm to the picture, once it's updated for Apps.

please let me know what you think?

**Comment by blackboxsw** [comment]
> ok, thanks @blackboxsw
> 
> in that case, I think that we should update the URL in the following 16.04 scenarios (please note that I excluded all UA Apps: ESM cases)
> 
> [1] APT
> *The following packages could receive security updates with UA Infra: ESM service enabled:
> libkrad0
> Learn more about UA Apps: ESM service **for Ubuntu 16.04** at https://ubuntu.com/16-04
> 
> [2] MOTD
> 1 additional security updates can be applied with UA Infra: ESM
> Learn more about enabling UA Apps: ESM service **for Ubuntu 16.04** at https://ubuntu.com/16-04
> 
> I think that only those 2 scenarios are covering the initial discovery. Beyond that, I'd point people directly to /advantage. I would consider adding /esm to the picture, once it's updated for Apps.
> 
> please let me know what you think?

@lechsandecki thanks this clarifies a lot and simplifies the messaging logic which makes sense in the context of initial discovery +1. I'm interpreting your comment: "(please note that I excluded all UA Apps: ESM cases)" to mean we will only do this for ESM Infra service and  not for Apps.

**Comment by blackboxsw** [comment]
@lucasmoura note @lechsandecki's second comment here changes the text in update-notifier pkg per your existing PR at https://code.launchpad.net/~lamoura/update-notifier/+git/update-notifier/+merge/402163

which would need to add "for Ubuntu 16.04 at https://ubuntu.com/16-04" on lts releases which are in active esm.

[2] MOTD
1 additional security updates can be applied with UA Infra: ESM
Learn more about enabling UA Apps: ESM service for Ubuntu 16.04 at https://ubuntu.com/16-04

**Comment by lucasmoura** [comment]
@blackboxsw @lechsandecki I have added that change to the `update-notifier` PR
