### ISSUE TITLE
bionic: transition from pre-EOL to post-EOL handle installing unauthenticated apt sources for ESM* packages

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1587]
Need a service/utility/script that will properly check transition from pre-EOL to post-EOL to ensure ESM APT files are properly setup on unattached systems:
[This logic is only in effect during pkg upgrade](https://github.com/canonical/ubuntu-advantage-client/blob/release-27/debian/ubuntu-advantage-tools.postinst#L230)

We need trigger that will allow ESM-infra APT sources to get written to enable unauthenticated visibility to ESM-infra pkgs once Bionic is EOL(start of ESM-infra)

**Comment by orndorffgrant** [comment]
Tracking in SC-665
