### ISSUE TITLE
trusty upgrade to xenial will show esm-infra as disabled

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-advantage-client#1590]
When we are attached to a trusty machine and we perform a `do-release-upgrade` operation we expect to be upgraded to xenial while keeping `esm-infra`, or any other service we have enabled, still enabled. We guarantee that by running the [upgrade_lts_contract](https://github.com/canonical/ubuntu-advantage-client/blob/main/lib/upgrade_lts_contract.py) in the end of `do-release-upgrade`. This is script is run by adding the following configuration at `/etc/update-manager/release-upgrades.d/`

```
[Sources]
Pockets=security,updates,proposed,backports,infra-security,infra-updates,apps-security,apps-updates
[Distro]
PostInstallScripts=./xorg_fix_proprietary.py, /usr/lib/ubuntu-advantage/upgrade_lts_contract.py
```

In our current testing infrastructure, we are updating the tusty packaging to the development version of uaclient and then performing the upgrade. This will guarantee that will we have that file in place before running `do-release-upgrade`. Now, since we will not release the new uaclient version into trusty, we will never have that configuration in place. This means that `do-release-upgrade`  will not run the `upgrade_lts_script` in the end, which in turn, will make `esm-infra` to be disabled, as the apt sources will not be correctly updated.

**Comment by lucasmoura** [comment]
We two workarounds for this:

1) Manually add the `etc/update-manager/release-upgrades.d/` config:
```
[Sources]
Pockets=security,updates,proposed,backports,infra-security,infra-updates,apps-security,apps-updates
[Distro]
PostInstallScripts=./xorg_fix_proprietary.py, /usr/lib/ubuntu-advantage/upgrade_lts_contract.py
```

Before running `do-release-upgrade`

2) After running `do-release-upgrade`  and restarting the machine, run `ua enable esm-infra`

**Comment by mitechie** [comment]
Documented as an FAQ item in https://discourse.ubuntu.com/t/ubuntu-advantage-client/21788/4

**Comment by orndorffgrant** [comment]
Closing as a Won't Fix because it is documented.
