### ISSUE TITLE
incomplete message - This machine is now attached to ''

### ISSUE THREAD

**Issue by cpaelzer** [canonical/ubuntu-advantage-client#1592]
Hi,
maybe my token/ID is bad, but on all machines that I activated my token I've got

```
sudo ua attach you-wont-get-my-token-unless-you-need-for-debug
This machine is now attached to ''

SERVICE       ENTITLED  STATUS    DESCRIPTION
esm-infra     yes       n/a       UA Infra: Extended Security Maintenance (ESM)
fips          yes       disabled  NIST-certified FIPS modules
fips-updates  yes       disabled  Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service

NOTICES
Operation in progress: ua attach

Enable services with: ua enable <service>

     Account: 
Subscription: 
```

Wondering about:
 - attached to ''
 - Account: 
 - Subscription: 

Some data seems to be missing here, it isn't that the attach didn't work. IF I try to attach again I get:

```
sudo ua attach you-wont-get-my-token-unless-you-need-for-debug
This machine is already attached to ''
To use a different subscription first run: sudo ua detach.
```

**Comment by cpaelzer** [comment]
FYI from looking at other issues, this seems to be a more severe form of issue #1547

**Comment by cpaelzer** [comment]
Further FYI - I've only tested on various s390x and ppc64el machines so far.
But a recheck on x86 xenial container showed that it isn't arch-specific (more likely to be my token/account)

**Comment by cpaelzer** [comment]
FYI x86 output (since it enables a few things by default)

```
sudo ua attach you-wont-get-my-token-unless-you-need-for-debug
Enabling default service esm-infra
Updating package lists
UA Infra: ESM enabled
A reboot is required to complete install.
Enabling default service livepatch
Installing canonical-livepatch snap
Canonical livepatch enabled.
This machine is now attached to ''

SERVICE       ENTITLED  STATUS    DESCRIPTION
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips          yes       disabled  NIST-certified FIPS modules
fips-updates  yes       disabled  Uncertified security updates to FIPS modules
livepatch     yes       enabled   Canonical Livepatch service

NOTICES
Operation in progress: ua attach

Enable services with: ua enable <service>

     Account: 
Subscription
```

**Comment by mitechie** [comment]
This seems to be related to how the company-specific tokens are set up in the contract service. We're investigating this longer term but I don't believe is true of typical customers. We'll make sure to sync with them if there's an easy way to update those tokens without invalidating/respinning them.

**Comment by cmars** [comment]
@cpaelzer I'll need to get some details from you about your account, so I'll ping in a DM on company chat. Will update this bug with  my findings (it's likely not a UA client issue).

**Comment by cmars** [comment]
Looking at the account synced from Salesforce on the shop backend for this user account -- it looks like the account name is indeed missing there (coming across as an empty string). So I think the UA client is displaying the contract information correctly.

We're investigating why this account has an empty name. At this point, it's definitely a backend issue. possibly related to our SF integration.
