### ISSUE TITLE
Please recheck on the wording for non supported features/platforms

### ISSUE THREAD

**Issue by cpaelzer** [canonical/ubuntu-advantage-client#1593]
I know there was a lot of bike-shedding and polishing so this is just a re-check to be sure.
esm-infra per the [service terms](https://ubuntu.com/legal/ubuntu-advantage-service-description) is x86 only.

So I properly get what I'd expect:

```
$ sudo ua enable esm-infra
One moment, checking your subscription first
UA Infra: ESM is not available for platform s390x.
Supported platforms are: amd64, i386, i686, x86_64.
```

But after just `ua attach` it looks like

```
esm-infra     yes       n/a       UA Infra: Extended Security Maintenance (ESM)
```

To me that looks a bit like "you would be able to use" to then say "sorry, but no" later on.
Really I don't want to kick off any new bike-shedding - just asking if the output as presented is as decided in the design documents.

**Comment by orndorffgrant** [comment]
Thanks for the feedback! This is output is as intended. It means "your contract is entitled to this service, but it is not applicable to this machine".
We'll leave it as is unless we get more confused customers.
