### ISSUE TITLE
Modify update-notifier to not show esm-infra and apps messaging at once (SC-14)

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-advantage-client#1602]
If we have the sources of both `esm-infra`  and `esm-apps`  and they are both disabled services, we would show both infra and apps alerts in update-notifier. Something like this:

```
Enable UA Apps: ESM to receive additional future security updates.
See https://ubuntu.com/security/esm or run: sudo ua status

Enable UA Infra: ESM to receive additional future security updates.
See https://ubuntu.com/security/esm or run: sudo ua status
```

We want to avoid those two alerts by:

1. Only showing the `esm-infra` alert if the distro is ESM
2. Only show the `esm-apps` alert if the distro is LTS and not ESM

**Comment by orndorffgrant** [comment]
@lucasmoura We can mark this done right?

**Comment by lucasmoura** [comment]
Yes, we can
