### ISSUE TITLE
CI: add hirsute and focal coverage for integration tests. 

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1604]
Right now there are limited number of CI scenarios for Focal and none for Hirsute. Extend existing behave scenario tests where applicable for both hirsute and focal.

**Comment by orndorffgrant** [comment]
@lucasmoura Is this also done as of #1611 being merged?

**Comment by lucasmoura** [comment]
Yes, I think we can close it as well. Thank you @orndorffgrant
