### ISSUE TITLE
tests: drop trusty tests

### ISSUE THREAD

**Issue by orndorffgrant** [canonical/ubuntu-advantage-client#1605]
We are not going to release any new versions of ua to trusty, so we don't need to keep testing on trusty.

We need to move any tests that only exist for trusty and will still be helpful to xenial. The rest can be deleted.

**Comment by orndorffgrant** [comment]
@lucasmoura Can this be closed since #1611 was merged?

**Comment by lucasmoura** [comment]
Yes, we can close it
