### ISSUE TITLE
Enabling livepatch should log that snapd does not have wait command

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-advantage-client#1616]
We have a [Launchpad bug](https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1927329) that states a problem running `ua enable livepatch` when the snapd package does not have the `wait` command. This can happen on older machines, were snapd is not updated to the latest release.

If we identify that, we should not fail enabling livepatch. We should log that snapd is not updated and try to enable the service. If enabling it fails, users will be able to look at the logs and see that maybe the reason was because we could not run snapd wait command

**Comment by orndorffgrant** [comment]
Fixed by #1621
