### ISSUE TITLE
Cannot enable cis on Ubuntu Pro 20.04

### ISSUE THREAD

**Issue by davecore82** [canonical/ubuntu-advantage-client#1622]
It's not possible to enable the cis beta feature with the ua client in Ubuntu Pro 20.04.

Tried with the latest ubuntu-advantage-tools 27.0-1066~ga4c4fab~ubuntu20.04.1 package from the UA Client Daily PPA.

```
ubuntu@focalpro2021-05-11-08-24-21:~$ ua version
27.0-1066~ga4c4fab~ubuntu20.04.1

ubuntu@focalpro2021-05-11-08-24-21:~$ sudo ua enable cis --beta
One moment, checking your subscription first
CIS Audit is not available for Ubuntu 20.04 LTS (Focal Fossa).
```

The Canonical CIS tooling for 20.04 was just recently certified by CIS and launched. It's currently available in the security benchmark PPA that's available with Ubuntu Advantage purchases, but it's not yet available in the deb repositories available in Ubuntu Pro.

I understand this cis feature should be available in beta in the 27.1 release of ubuntu-advantage-tools. 

In the meantime, users can request access to the private PPA with the CIS tooling for 20.04 by following the steps in https://security-certs.docs.ubuntu.com/en/cis#obtaining-the-cis-compliance-tools-from-canonical.  But instead of using the support portal, they should file a request here:  https://forms.canonical.com/bitstream/  

FYI the CIS tooling is available on Ubuntu Pro 18.04 and 16.04.

**Comment by blackboxsw** [comment]
ubuntu-advantage-tools v 27.1 just published to yesterday Xenial, Bionic, Focal, Groovy and Hirsute which removed the --beta flag requirement for enabling CIS.


I just confirmed success for CIS on 20.04 with ua-tools v.27.1

```bash
root@amused-snapper:~# ua attach <REDACTED>
Enabling default service esm-infra
Updating package lists
UA Infra: ESM enabled
This machine is now attached to 'chad.smith@canonical.com'

SERVICE       ENTITLED  STATUS    DESCRIPTION
cis           yes       disabled  Center for Internet Security Audit Tools
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips          yes       n/a       NIST-certified core packages
fips-updates  yes       n/a       NIST-certified core packages with priority security updates
livepatch     yes       n/a       Canonical Livepatch service

NOTICES
Operation in progress: ua attach

Enable services with: ua enable <service>

     Account: chad.smith@canonical.com
Subscription: chad.smith@canonical.com
root@amused-snapper:~# ua enable cis
One moment, checking your subscription first
Updating package lists
Installing CIS Audit packages
CIS Audit enabled
Visit https://security-certs.docs.ubuntu.com/en/cis to learn how to use CIS
root@amused-snapper:~# ua version
27.1~20.04.1
```
