### ISSUE TITLE
More detailed error messages when attachment fails with a 403 (SC-3)

### ISSUE THREAD

**Issue by alnvdl** [canonical/ubuntu-advantage-client#1630]
We've recently introduced slightly more detailed error messages in ua-contracts when machine attachment fails because the contract is not valid. The reason for that was because of customers who were trying to attach machines to their contracts before they became effective. In that case, the client gives them a generic error message directing them to `/advantage`.

We'd like to have this changed to a more informative error message, possibly explaining that their contracts are not valid yet (or if they expired already). Pointing them to `/advantage` can still happen, but it'd be nice to also directly show the actual reason we are denying attachment.

The messages look like this (the wording on the messages could be changed if you'd like something different):
```
Body: {
  "code": "forbidden",
  "message": "contract \"cAPWbzTkpV9EGQnTky8QDUtSDl5KRZO5B6R6PnpHoX0M\" not effective: contract not effective",
  "traceId": "9525486a-82ea-4521-b491-47ef34517e4b"
}
```
And this:
```
Body: {
  "code": "forbidden",
  "message": "contract \"cAJsI3QwlhB7VnJZFaHgXCw-RnsvQam_coYmqz5l9Ekw\" not effective: contract will become effective on 2021-10-01 00:00:00 +0000 UTC",
  "traceId": "5eda9bff-5530-419f-8a1d-202f7193f0c6"
}
```

---

Below is a guide on how you can replicate these scenarios using [the contract client](https://github.com/CanonicalLtd/ua-contracts/tree/develop/cmd/contract):

The expired case:
```
export CONTRACTS_URL="https://contracts.staging.canonical.com/"

echo '{"name": "test-attach-expired"}' | contract call add-account -

echo '{
    "name": "test-contract",
    "products": ["free"],
    "items": [{
        "effectiveFrom": "2020-06-01T00:00:00Z",
        "effectiveTo": "2020-10-01T00:00:00Z",
        "reason": "sf_asset_created",
    }]
}' | contract call add-account-contract <account-id-from-previous-step> - --verbose

echo '{}' | contract call get-contract-token <contract-id-from-previous-step> - --verbose

echo '{}' | contract -a token:<contract-token-from-previous-step> call add-contract-machine - --verbose
```
Result:
```
RESPONSE
Status: 403 Forbidden
Cache-Control: no-store, max-age=0
Content-Length: 177
Content-Type: application/json
Date: Wed, 12 May 2021 23:28:40 GMT
Server: openresty/1.15.8.2
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Trace-Id: 9525486a-82ea-4521-b491-47ef34517e4b
Body: {
  "code": "forbidden",
  "message": "contract \"cAPWbzTkpV9EGQnTky8QDUtSDl5KRZO5B6R6PnpHoX0M\" not effective: contract not effective",
  "traceId": "9525486a-82ea-4521-b491-47ef34517e4b"
}
```

---

The not-yet valid case:
```
export CONTRACTS_URL="https://contracts.staging.canonical.com/"

echo '{"name": "test-attach-not-yet-valid"}' | contract call add-account -

echo '{
    "name": "test-contract",
    "products": ["free"],
    "items": [{
        "effectiveFrom": "2021-10-01T00:00:00Z",
        "effectiveTo": "2021-12-01T00:00:00Z",
        "reason": "sf_asset_created",
    }]
}' | contract call add-account-contract <account-id-from-previous-step> - --verbose

echo '{}' | contract call get-contract-token <contract-id-from-previous-step> - --verbose

echo '{}' | contract -a token:<contract-token-from-previous-step> call add-contract-machine - --verbose
```
Result:
```
RESPONSE
Status: 403 Forbidden
Cache-Control: no-store, max-age=0
Content-Length: 218
Content-Type: application/json
Date: Wed, 12 May 2021 23:34:41 GMT
Server: openresty/1.15.8.2
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Trace-Id: 5eda9bff-5530-419f-8a1d-202f7193f0c6
Body: {
  "code": "forbidden",
  "message": "contract \"cAJsI3QwlhB7VnJZFaHgXCw-RnsvQam_coYmqz5l9Ekw\" not effective: contract will become effective on 2021-10-01 00:00:00 +0000 UTC",
  "traceId": "5eda9bff-5530-419f-8a1d-202f7193f0c6"
}
```

**Comment by orndorffgrant** [comment]
@alnvdl Thanks for letting us know about these new error messages! I'm always a fan of giving the user more useful information. I put up a first draft PR of incorporating these messages into our output when attach fails in #1638 

Right now, it ends up looking something like this:
for the expired case:
```
Attach denied for reason:
contract "cAEHtYFZhemdwTIaWmoFRO9YiByPAtKGoNjbEpr433eQ" not effective: contract
not effective
Visit https://ubuntu.com/advantage to manage contract tokens.
```
and for the not yet active case:
```
Attach denied for reason:
contract "cAD-KwqGB24sG-9tm81cmTVlF77RcNflLn7WAbXGBMcY" not effective: contract
will become effective on 2021-09-30 20:00:00 -0400 EDT
Visit https://ubuntu.com/advantage to manage contract tokens.
```
@mitechie I'm hoping to get your opinion on the the above output in addition to my comments below:

I have two comments/questions for @alnvdl on the message content:
1. Is the contract ID useful information for the user? For example, can they use this ID when they go to ubuntu.com/advantage to identify which contract is expired? If not, then we may not want to display it to the user.
2. The messages are worded a little redundantly. This is most clear in the expired case above. It essentially says "contract not effective" twice.

And if the conversation on the content of these messages should happen elsewhere (like on the ua-contracts repo) just let me know :)

**Comment by mitechie** [comment]
Can we say expired when it's expire vs "effective"? I feel that expired is a more clear explanation and maybe we can mirror the time of the other message by stating

    Attach denied:
    contract "cAEHtYFZhemdwTIaWmoFRO9YiByPAtKGoNjbEpr433eQ" expired on August 30th, 2021
    Visit https://ubuntu.com/advantage to manage contract tokens.

and the mirror would be

    Attach denied:
    contract "cAEHtYFZhemdwTIaWmoFRO9YiByPAtKGoNjbEpr433eQ" is not effective until August 30th, 2021
    Visit https://ubuntu.com/advantage to manage contract tokens.

What do you think?

**Comment by orndorffgrant** [comment]
I do like those messages better.

As currently implemented, these messages would need to be updated on the contract server.

Alternatively, the contract server could be modified to return this information in a more structured way and uaclient could format it. For example, if the server returned:
```json
{
  "code": "forbidden",
  "contractId": "cAJsI3QwlhB7VnJZFaHgXCw-RnsvQam_coYmqz5l9Ekw",
  "reason": "not_effective_yet",
  "effectiveDate": "2021-10-01 00:00:00 +0000 UTC",
  "traceId": "5eda9bff-5530-419f-8a1d-202f7193f0c6"
}
```
Then we could parse it and format the appropriate message ("is not effective until" in this case). However, this might be adding too much complexity just for this feature.

**Comment by mitechie** [comment]
@orndorffgrant can we please then file a bug upstream to the contract service project to request the dates added into the response so we can build the proper messaging please?

**Comment by orndorffgrant** [comment]
Just opened https://github.com/CanonicalLtd/ua-contracts/issues/2059
