### ISSUE TITLE
CIS: remove beta service status from CIS

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1641]
Adding an integration test for "cis-audit lvl1_server" running the audit utility in the integration test.

We probably want to avoid actually running the hardening script in a frequent integration test (maybe a one-off for SRU verification) because it takes a long time to make filesystem/service changes to re-configure the machine.

**Comment by orndorffgrant** [comment]
Completed with #1644
Closing
