### ISSUE TITLE
`ua enable fips` failure -- Packages Downgraded error

### ISSUE THREAD

**Issue by arossbell** [canonical/ubuntu-advantage-client#1659]
A customer opened a case against an Ubuntu image (non-PRO) on AWS GovCloud that `ua enable fips` fails.
Without debug messages, a quiet error.
```
# ua enable fips
One moment, checking your subscription first
Installation of additional packages are required to make this system FIPS
compliant.
Are you sure? (y/N) y
FIPS cannot be enabled with Livepatch.
Disable Livepatch and proceed to enable FIPS? (y/N)y
Disabling incompatible service: Livepatch
Updating package lists
Installing FIPS packages
Updating package lists
Could not enable FIPS.
```

But among debug messages, the issue is clear. (Also including more information about the system.)
```
# ua --debug enable fips
[ . . . ]
{'Authorization': 'Bearer <REDACTED>', 'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'UA-Client/27.0.2~18.04.1'}, data: {"machineId": "<REDACTED>", "architecture": "amd64", "os": {"distribution": "Ubuntu", "type": "Linux", "version": "18.04 LTS (Bionic Beaver)", "release": "18.04", "series": "bionic", "kernel": "5.4.0-1048-aws"}}
[ . . . ]
DEBUG: Failed running command 'apt-get install --assume-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" ubuntu-fips openssh-client openssh-client-hmac openssh-server openssh-server-hmac openssh-client openssh-client-hmac openssh-server openssh-server-hmac' [exit(100)]. Message: E: Packages were downgraded and -y was used without --allow-downgrades.
[ . . . ]
```

**Comment by mitechie** [comment]
Thank you for the bug report. We'll investigate and get back. If possible can you confirm the ua client version and ubuntu system details, such as the VM id used to launch the instance? 

    ua --version

Thank you!

**Comment by arossbell** [comment]
Hi @mitechie,

The package is versioned `27.0.2~18.04.1` and the build.info serial from the server system is `20190212.1`

Thanks!

**Comment by orndorffgrant** [comment]
@arossbell Thanks for the additional info. Do we also know what versions of the listed packages were before attempting to enable fips? `openssh-client` `openssh-client-hmac` `openssh-server` `openssh-server-hmac`

**Comment by arossbell** [comment]
Hi @orndorffgrant,

Before the FIPS enable process was attempted, the following are likely the versions. (These are from after the `ua enable fips` process failed, but before FIPS was manually installed)

openssh-client - `1:7.6p1-4ubuntu0.3`
openssh-server -  `1:7.6p1-4ubuntu0.3`
(-hmac packages absent from the system)

**Comment by orndorffgrant** [comment]
Part of this bug may be that we failed to detect that the instance was on aws. When we detect aws, we should install `ubuntu-aws-fips`, but the logs show that we tried to install `ubuntu-fips`. This may be a gap in our code not recognizing govcloud.
