### ISSUE TITLE
404 Error on link for ua-contracts openapi spec

### ISSUE THREAD

**Issue by reelieuglie** [canonical/ubuntu-advantage-client#1683]
Quick one. 

This link in README.md returns a 404 Error:
https://github.com/CanonicalLtd/ua-contracts/blob/develop/docs/contracts.yaml

It is found in the architecture section linked below, in the last line of the 4th paragraph:
https://github.com/canonical/ubuntu-advantage-client#architecture
"The contract server API is described by the [ua-contracts openapi spec](https://github.com/CanonicalLtd/ua-contracts/blob/develop/docs/contracts.yaml)."

Can't seem to find the proper URL either; both from searching Github and Google.

**Comment by mitechie** [comment]
Thanks, I've removed the broken link.
