### ISSUE TITLE
Ubuntu 20.04 Pro AMI "Operation in progress: ua auto-attach"

### ISSUE THREAD

**Issue by smalldave** [canonical/ubuntu-advantage-client#1749]
Using packer to build an image in AWS based on ami-0a883f9bbac0ac213 (Ubuntu 20.04 Pro).

I'm trying to run "ua enable cis --beta"

but I constantly get the message "Operation in progress: ua auto-attach".

I've tried waiting for the message to go. 
I've tried detaching (get the above message)
I've tried auto-attach (get the same message).

If I ssh into an instance based on the above image the message is there but does go eventually.
Doesn't seem to happen (at least not within 5 minutes) using packer.
When I have an interactive session ua status does show that I am entitled to enable CIS and it works when 
I do enable it.

Am I doing something silly?

**Comment by lucasmoura** [comment]
Hi @smalldave for PRO images, we run `auto-attach` when the instance is booted. We also perform this block that you are seeing to avoid the user issuing commands that may conflict with an already running ua service.

You could look at `/var/log/ubuntu-advantage.log` to see on which step the command is hanging. But if the logs are too noisy after all the commands you tried, my suggestion is to manually disable running auto-attach during boot by creating an image with this extra config on `/etc/ubuntu-advantage/uaclient.conf`:

```yaml
features:
  disable_auto_attach: true
```

You can then run the command manually after the machine is booted  to see which step it is being blocked

**Comment by orndorffgrant** [comment]
Hi @smalldave I'm going to close this bug because of inactivity. If you are still having problems feel free to re-open this and we will try to help out :)
