### ISSUE TITLE
/advantage page takes a long time to load when signed into SSO account

### ISSUE THREAD

**Issue by ariannalozano** [canonical/ubuntu-advantage-client#1773]
Hi Team, 

It is often that our Customer Success team and our VP of Marketing have difficulty accessing the UA dashboard simply because it does not ever load in our browser and seems to get stuck on a blank white page. This primarily happens when we are signed into our Canonical Ubuntu SSO. When signed in, I also recently received a 505 error code while trying to access the site during a customer onboarding presentation, which I don't think created a good impression for our customers.

This issue seems to be very intermittent, but can someone from the team please investigate further to see if the SSO could be interfering with the performance of this site?

**Comment by SirSamTumless** [comment]
Hi @ariannalozano This is the wrong repo, I will move it and we can address in in tomorrows standup.

**Comment by orndorffgrant** [comment]
Closing here since it was moved to the proper repo.
