### ISSUE TITLE
ua enable cc-eal2 doesn't work on 18.04

### ISSUE THREAD

**Issue by nmav** [canonical/ubuntu-advantage-client#1794]
We have already a CC profile for 18.04 but ua client doesn't enable it yet. The cc-eal2 option is not available and even when `--beta` is set it doesn't allow enabling it.

https://ubuntu.com/security/cc

**Comment by orndorffgrant** [comment]
Thanks for opening the issue @nmav!

The contract server will need to update the entitlement definition to allow CC on bionic. Also, it doesn't look like the cc packages are available for bionic yet here https://esm.ubuntu.com/cc/ubuntu/dists/

I recommend you work with @frankban and IS to get CC for bionic available on esm.ubuntu.com and allowed via the contract server - at that point it _should_ "just work" with `ua enable`

**Comment by nmav** [comment]
Thank you @orndorffgrant is that the reason that `--beta` is required for it?

**Comment by blackboxsw** [comment]
@nmav I believe it was just that it was lower priority than ESM Apps enablement and Rick wanted us to focus on that feature work first before addressing CC-EAL.   That said, if we want to prioritize validation of CC-EAL support in Xenial and Bionic the following things are needed to get out of non-beta:

* To confirm for Nikos or Lech? the simple post-install message from UA client is the desired usability for customers: Please follow instructions in /usr/share/doc/ubuntu-commoncriteria/README to configure EAL2
add the right gpg to ua-tools key for cc-eal
* Fix the package install problems with common-criteria on xenial
* drop the is_beta in uaclient.entitlements.cc and add integration tests for production behavior enabling CC-EAL
* Update docs with security team: https://ubuntu.com/security/certifications/docs/cc to reference UA install steps

**Comment by blackboxsw** [comment]
Those first 4 bullets are all handled by discussions with you and Lech plus  single PR against ua-client that should be low hanging fruit. The unknown is the current install error we see on Xenial and whether that implies a packaging change. Also, bionic support would rely on someone driving APT repo setup through the IS team (and Commercial Services)  on esm.ubuntu.com/cc to get bionic APT suites  represented with updated ubuntu-commoncriteria packages.

**Comment by nmav** [comment]
Ok, so if I understand well, ua with CC has not worked yet, so it is not about 18.04 only, but also 16.04. This is not then urgent, let me discuss with the security team and I'll come back.
