### ISSUE TITLE
AWS t4g.nano apt-get update ubuntu-advantage-tools failures

### ISSUE THREAD

**Issue by Conrad-T-Pino** [canonical/ubuntu-advantage-client#1888]
Excerpt from `sudo apt-get update`:
>`Setting up ubuntu-advantage-tools (27.4.1~20.04.1) ...`
>`Installing new version of config file /etc/ubuntu-advantage/uaclient.conf ...`
>`Traceback (most recent call last):`
>`  File "<string>", line 10, in <module>`
>`KeyError: 'status'`
>`Traceback (most recent call last):`
>`  File "<string>", line 10, in <module>`
>`KeyError: 'status'`
>`Setting up libaccountsservice0:arm64 (0.6.55-0ubuntu12~20.04.5) ...`

Failing `sudo apt-get reinstall ubuntu-advantage-tools`:
>`Reading package lists... Done`
>`Building dependency tree`
>`Reading state information... Done`
>`0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.`
>`Need to get 0 B/783 kB of archives.`
>`After this operation, 0 B of additional disk space will be used.`
>`Preconfiguring packages ...`
>`(Reading database ... 109055 files and directories currently installed.)`
>`Preparing to unpack .../ubuntu-advantage-tools_27.4.1~20.04.1_arm64.deb ...`
>`Unpacking ubuntu-advantage-tools (27.4.1~20.04.1) over (27.4.1~20.04.1) ...`
>`Setting up ubuntu-advantage-tools (27.4.1~20.04.1) ...`
>`Traceback (most recent call last):`
>`  File "<string>", line 10, in <module>`
>`KeyError: 'status'`
>`Traceback (most recent call last):`
>`  File "<string>", line 10, in <module>`
>`KeyError: 'status'`
>`Processing triggers for man-db (2.9.1-1) ...`

Repositories: `egrep -v "^[[:blank:]]*(#|$)" /etc/apt/sources.list`:
>`deb http://us.ports.ubuntu.com/ubuntu-ports/ focal main restricted`
>`deb http://us.ports.ubuntu.com/ubuntu-ports/ focal-updates main restricted`
>`deb http://us.ports.ubuntu.com/ubuntu-ports/ focal universe`
>`deb http://us.ports.ubuntu.com/ubuntu-ports/ focal-updates universe`
>`deb http://us.ports.ubuntu.com/ubuntu-ports/ focal multiverse`
>`deb http://us.ports.ubuntu.com/ubuntu-ports/ focal-updates multiverse`
>`deb http://us.ports.ubuntu.com/ubuntu-ports/ focal-backports main restricted universe multiverse`
>`deb http://ports.ubuntu.com/ubuntu-ports focal-security main restricted`
>`deb http://ports.ubuntu.com/ubuntu-ports focal-security universe`
>`deb http://ports.ubuntu.com/ubuntu-ports focal-security multiverse`

Versions: `cat /etc/debian_version /etc/ec2_version`:
>`bullseye/sid`
>`Ubuntu 20.04.1 LTS (Focal Fossa)`

Versions:  `uname --all`:
>`Linux name 5.11.0-1021-aws #22~20.04.2-Ubuntu SMP Wed Oct 27 21:27:49 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

Versions: `lsb_release --all`:
>`No LSB modules are available.`
>`Distributor ID: Ubuntu`
>`Description:    Ubuntu 20.04.3 LTS`
>`Release:        20.04`
>`Codename:       focal`

Best regards,
Conrad T. Pino

**Comment by blackboxsw** [comment]
Thank you @Conrad-T-Pino for filling this bug. Some things I think we'd be curious about to understand this bug a bit more:

 1. contents of /etc/cloud/build.info if present  # to determine base cloud image you used_
 2. Your /var/log/ubuntu-advantage,log to show us history of UA commands run
- NOTE If your system was attached to a check /var/log/ubuntu-advantage.log to remove any values in logs shown related to "token" or "Token" because older versions of UA client didn't <REDACT> them automatically.
 3. contents of /var/lib/ubuntu-advantage/status.json on the system (as this is where the key error came from

Generally 2 & 3 can be obtained by running `ua collect-logs` which would create a compressed ua_logs.tar.gz in your current working directory.

**Comment by blackboxsw** [comment]
I also just filed https://github.com/canonical/ubuntu-advantage-client/issues/1889 which should help future folks to safely collect-logs and not worry about leaked credentials when filing bugs.

**Comment by Conrad-T-Pino** [comment]
@blackboxsw 

This host does not participate in Ubuntu Advantage program.
Issue does not replicate on `x86_64` host at same Ubuntu level.

Output from `cat /etc/cloud/build.info`:
>`build_name: server`
>`serial: 20201026`

Output from `sudo cat /var/log/ubuntu-advantage.log`:
>`2021-11-01 03:16:53,090 - ua_update_messaging.py:(347) [DEBUG]: Updating UA messages for APT and MOTD.`
>`2021-11-01 03:16:53,090 - util.py:(419) [DEBUG]: Reading file: /etc/os-release`
>`2021-11-01 03:16:53,100 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-01 03:16:53,101 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-01 03:16:53,107 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-01 03:16:53,107 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-01 15:14:24,470 - ua_update_messaging.py:(347) [DEBUG]: Updating UA messages for APT and MOTD.`
>`2021-11-01 15:14:24,471 - util.py:(419) [DEBUG]: Reading file: /etc/os-release`
>`2021-11-01 15:14:24,479 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-01 15:14:24,480 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-01 15:14:24,484 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-01 15:14:24,485 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-02 03:31:46,282 - ua_update_messaging.py:(347) [DEBUG]: Updating UA messages for APT and MOTD.`
>`2021-11-02 03:31:46,283 - util.py:(419) [DEBUG]: Reading file: /etc/os-release`
>`2021-11-02 03:31:46,290 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-02 03:31:46,290 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-02 03:31:46,296 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-02 03:31:46,296 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-02 15:05:07,246 - ua_update_messaging.py:(347) [DEBUG]: Updating UA messages for APT and MOTD.`
>`2021-11-02 15:05:07,247 - util.py:(419) [DEBUG]: Reading file: /etc/os-release`
>`2021-11-02 15:05:07,253 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-02 15:05:07,255 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-02 15:05:07,260 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-02 15:05:07,260 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-03 03:55:53,118 - ua_update_messaging.py:(347) [DEBUG]: Updating UA messages for APT and MOTD.`
>`2021-11-03 03:55:53,118 - util.py:(419) [DEBUG]: Reading file: /etc/os-release`
>`2021-11-03 03:55:53,131 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-03 03:55:53,131 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-03 03:55:53,136 - util.py:(419) [DEBUG]: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json`
>`2021-11-03 03:55:53,136 - config.py:(442) [DEBUG]: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json`

Output from `python3 -m json.tool /var/lib/ubuntu-advantage/status.json`:
>`{`
>`	"_doc": "Content provided in json response is currently considered Experimental and may change",`
>`	"_schema_version": "0.1",`
>`	"version": "27.3~20.04.1",`
>`	"machine_id": null,`
>`	"attached": false,`
>`	"effective": null,`
>`	"expires": null,`
>`	"origin": null,`
>`	"services": [`
>`		{`
>`			"name": "cc-eal",`
>`			"description": "Common Criteria EAL2 Provisioning Packages",`
>`			"available": "no"`
>`		},`
>`		{`
>`			"name": "cis",`
>`			"description": "Center for Internet Security Audit Tools",`
>`			"available": "no"`
>`		},`
>`		{`
>`			"name": "esm-apps",`
>`			"description": "UA Apps: Extended Security Maintenance (ESM)",`
>`			"available": "no"`
>`		},`
>`		{`
>`			"name": "esm-infra",`
>`			"description": "UA Infra: Extended Security Maintenance (ESM)",`
>`			"available": "no"`
>`		},`
>`		{`
>`			"name": "fips",`
>`			"description": "NIST-certified core packages",`
>`			"available": "no"`
>`		},`
>`		{`
>`			"name": "fips-updates",`
>`			"description": "NIST-certified core packages with priority security updates",`
>`			"available": "no"`
>`		},`
>`		{`
>`			"name": "livepatch",`
>`			"description": "Canonical Livepatch service",`
>`			"available": "no"`
>`		},`
>`		{`
>`			"name": "ros",`
>`			"description": "Security Updates for the Robot Operating System",`
>`			"available": "no"`
>`		},`
>`		{`
>`			"name": "ros-updates",`
>`			"description": "All Updates for the Robot Operating System",`
>`			"available": "no"`
>`		}`
>`	],`
>`	"execution_status": "inactive",`
>`	"execution_details": "No Ubuntu Advantage operations are running",`
>`	"notices": [],`
>`	"contract": {`
>`		"id": "",`
>`		"name": "",`
>`		"created_at": "",`
>`		"products": [],`
>`		"tech_support_level": "n/a"`
>`	},`
>`	"account": {`
>`		"name": "",`
>`		"id": "",`
>`		"created_at": "",`
>`		"external_account_ids": []`
>`	},`
>`	"config_path": "/etc/ubuntu-advantage/uaclient.conf",`
>`	"config": {`
>`		"contract_url": "https://contracts.canonical.com",`
>`		"security_url": "https://ubuntu.com/security",`
>`		"data_dir": "/var/lib/ubuntu-advantage",`
>`		"log_level": "debug",`
>`		"log_file": "/var/log/ubuntu-advantage.log",`
>`		"timer_log_file": "/var/log/ubuntu-advantage-timer.log",`
>`		"license_check_log_file": "/var/log/ubuntu-advantage-license-check.log",`
>`		"ua_config": {`
>`			"apt_http_proxy": null,`
>`			"apt_https_proxy": null,`
>`			"http_proxy": null,`
>`			"https_proxy": null,`
>`			"update_messaging_timer": 21600,`
>`			"update_status_timer": 43200,`
>`			"metering_timer": 0`
>`		}`
>`	}`
>`}`

Best regards,
Conrad T. Pino
