### ISSUE TITLE
KeyError: 'status' during package upgrade (even when client is not used)

### ISSUE THREAD

**Issue by lathiat** [canonical/ubuntu-advantage-client#1899]
While doing a simple 'apt upgrade' on my arm64 multipass Ubuntu 20.04 VM I got the following errors:
```
Unpacking ubuntu-advantage-tools (27.4.1~20.04.1) over (27.3~20.04.1) ...
Setting up ubuntu-advantage-tools (27.4.1~20.04.1) ...
Installing new version of config file /etc/ubuntu-advantage/uaclient.conf ...
Traceback (most recent call last):
  File "<string>", line 10, in <module>
KeyError: 'status'
Traceback (most recent call last):
  File "<string>", line 10, in <module>
KeyError: 'status'
```

The VM is not attached and I haven't really used the tools, they are just there from a default install.

If I had to guess looking at /var/lib/dpkg/info/ubuntu-advantage-tools.postinst it's highly likely the check_service_is_enabled function was at fault since on line 10 it accesses the key 'status'. I am guessing this status-cache before the upgrade was not yet populated with the keys it required.

```
check_service_is_enabled() {
    service_name=$1
    _RET=$(/usr/bin/python3 -c "
import os
import json
from uaclient.config import UAConfig
cfg = UAConfig()
status = cfg.read_cache('status-cache')
if status:
    for service in status['services']:
       if service['name'] == '${service_name}':
           print(service['status'])
")
   if [ "${_RET}" = "enabled" ]; then
       return  0
   else
       return  1
   fi
}
```

**Comment by lathiat** [comment]
Can reproduce even after the upgrade:

```
# 
root@primary:/var/lib/dpkg/info# check_service_is_enabled esm-infra
Traceback (most recent call last):
  File "<string>", line 10, in <module>
KeyError: 'status'
```

Looking at the output from 'cat /var/lib/ubuntu-advantage/status.json|jq .services' the key doesn't exist:
```
  {
    "name": "esm-infra",
    "description": "UA Infra: Extended Security Maintenance (ESM)",
    "available": "no"
  },
```

**Comment by renanrodrigo** [comment]
@lathiat thanks for reporting it.
This is a valid issue, and it is fixed in version `27.4.2`. It should be released and available this week. We will keep you posted about it.

**Comment by blackboxsw** [comment]
Related bug here https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1951705 which should publish/release on Monday.

**Comment by renanrodrigo** [comment]
@lathiat `27.4.2` is out, this should be fixed. Please feel free to reopen if it does not work your side.
