### ISSUE TITLE
`ua security-status` doesn't show packages that would be updated if connected to UA

### ISSUE THREAD

**Issue by robert-ancell** [canonical/ubuntu-advantage-client#2143]
On Ubuntu 18.04 `ua security-status` appears not to show any packages with status "pending_attach" when disconnected, i.e.

```
$ sudo ua attach <token>
$ ua security-status --format=json | jq .packages
[
  {
    "package": "libzmq5",
    "version": "4.2.5-1ubuntu0.2+esm2",
    "service_name": "esm-apps",
    "status": "upgrade_available",
    "origin": "esm.ubuntu.com"
  }
]
$ sudo ua detach
$ ua security-status --format=json | jq .packages
[]
```

**Comment by renanrodrigo** [comment]
Hello Robert, thanks for reporting it.
This is intended: ESM-Apps is not released yet, so ESM-Apps related updates are not shown unless you have it enabled.
When it gets officially released we will have the same logic that we got with ESM-Infra (show every update even if unattached).

**Comment by orndorffgrant** [comment]
Also, you can use our daily ppa for testing to start seeing these updates now: https://launchpad.net/~ua-client/+archive/ubuntu/daily
