### ISSUE TITLE
Return package size from `ua security-status`

### ISSUE THREAD

**Issue by robert-ancell** [canonical/ubuntu-advantage-client#2144]
Currently the name and version of updates are shown in `ua security-status`. It would be helpful to also get the size of the updates, so when showing this information in update-manager these updates look the same as the standard updates.

i.e. return something like:
```
{
  "package": "libzmq5",
  "version": "4.2.5-1ubuntu0.2+esm2",
  "size": 256228,
  "service_name": "esm-apps",
  "status": "upgrade_available",
  "origin": "esm.ubuntu.com"
}
```

The size value would be the "Size" field from the APT information (i.e. the download size), not the "Installed-Size" field.

**Comment by robert-ancell** [comment]
Context of how potential updates are shown:
![Screenshot from 2022-06-30 17-23-34](https://user-images.githubusercontent.com/126560/176599083-673ad7f8-a8e7-483d-bff6-aae50b771e27.png)

**Comment by orndorffgrant** [comment]
Thanks for the report @robert-ancell 
I'll add it as "download_size" to the output. 
We'll make sure this gets in our upcoming release.
