### ISSUE TITLE
usg not available for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by alkisg** [canonical/ubuntu-advantage-client#2245]
Hi, while trying to enable usg on Ubuntu 22.04 I'm getting the following error:

```console
root@server:~# ua status
SERVICE          ENTITLED  STATUS    DESCRIPTION
cc-eal           yes       n/a       Common Criteria EAL2 Provisioning Packages
esm-infra        yes       enabled   UA Infra: Extended Security Maintenance (ESM)
fips             yes       n/a       NIST-certified core packages
fips-updates     yes       n/a       NIST-certified core packages with priority security updates
livepatch        yes       enabled   Canonical Livepatch service
usg              yes       n/a       Security compliance and audit tools

Enable services with: ua enable <service>

     Account: alkisg@...
Subscription: alkisg@...

root@server:~# ua enable usg
One moment, checking your subscription first
Ubuntu Security Guide is not available for Ubuntu 22.04 LTS (Jammy Jellyfish).
```

Is this a temporary issue, are we waiting for it to be developed later on, and if so, any ETA?
Or did something replace it, and if so, what?
Thank you.

**Comment by renanrodrigo** [comment]
Hello, @alkisg - thanks for reporting this issue.
Nothing replaced USG, and I expect it will come to 22.04 eventually - but that's all I know.

The UA Client is only responsible for delivering USG and other services to platforms and systems where it is available.
I'd say your request would be better answered if reported in https://github.com/canonical/ubuntu-security-guide/

**Comment by alkisg** [comment]
Thank you @renanrodrigo, reported in https://github.com/canonical/ubuntu-security-guide/issues/15, closing this one.
