### ISSUE TITLE
Security scan warnings caused by file permissions on `/tmp/ubuntu-advantage/candidate-version`

### ISSUE THREAD

**Issue by aramprice** [canonical/ubuntu-advantage-client#2294]
The file `/tmp/ubuntu-advantage/candidate-version` is created with broad permissions ( [hard-coded to `777`](https://github.com/canonical/ubuntu-advantage-client/blob/main/uaclient/version.py#L670)).

This causes security scans to fail, specifically because of the world-writeable setting (`o+w`).

Based on usage in [`get_last_known_candidate()`](https://github.com/canonical/ubuntu-advantage-client/blob/main/uaclient/version.py#L51-L69) it seems like this file could be written with, at most `664` permissions if not more restrictive permissions. 

This change appears to have been introduced here https://github.com/canonical/ubuntu-advantage-client/commit/ce808efa9fe4120e81d0424f4d9978da2f00cb78

**Comment by orndorffgrant** [comment]
Thanks for the report! That slipped through review and was unintentional. We'll fix it in the next release. I think `644` is plenty.

**Comment by aramprice** [comment]
That's great news. Thank you.

**Comment by renanrodrigo** [comment]
Whoops :|
Grant is right, that was there for testing the first iterations of the feature, should have been changed.
