### ISSUE TITLE
$ sudo ua disable esm: Cannot disable unknown service 'esm'.

### ISSUE THREAD

**Issue by iconoclasthero** [canonical/ubuntu-advantage-client#2457]
```
$ sudo ua disable esm
Cannot disable unknown service 'esm'.
See https://ubuntu.com/pro
```
Per the man file:  **disable** [cc-eal|cis|**esm**|fips|fips-updates|livepatch|ros|ros-updates] 
[_emphasis added_]

Either the man file is broken or ua/pro/ubuntu-advantage is.   If the command should be \`ua disable esm-**_something_**` then the man file should specify that (e.g., exactly like ros-update does!).

**Comment by iconoclasthero** [comment]
NB: if you got here looking for a way to disable the MOTD advertising x number of updates via ESM, this isn't the right way.  See the accepted answer here: https://askubuntu.com/questions/1453749/inhibit-esm-messages-at-login

**Comment by renanrodrigo** [comment]
Hello, thanks for reporting this issue.
Yes, the manpage is wrong - will update it.

**Comment by renanrodrigo** [comment]
side note: to see the services you can enable/disable using the pro client, run `pro status`. To see beta and unavailable services, run `pro status --all`.
