### ISSUE TITLE
`ua` command to ease collection of debug data relating to the client

### ISSUE THREAD

**Issue by OddBloke** [canonical/ubuntu-advantage-client#463]
If/when a user ends up needing support or hitting a bug in the client, it would make both the development team's and the support team's lives easier if there were a clear mechanism to collect data for debugging from an affected system.

`cloud-init` has the `collect-logs` subcommand, and I think `ua collect-logs` would make sense too.

**Comment by BryanQuigley** [comment]
Either way +1.  I read it two different ways:

1.  A defined way to have ua send out relevant logs for debugging the client itself.  (Sosreport would that gain the ability to run this command)
2.  A tool to help the user run sosreport to collect information before sending it to support. RH's support tool has the ability to open a case with support and upload a sosreport/specific logs to it.

If we want to do both, the only thing to consider is how to name them so they do the obvious variant.

**Comment by OddBloke** [comment]
Thanks for that comment Bryan; I've modified the title and description to make it clear that this is your "1.".
