### ISSUE TITLE
Duplicate console logging setup in `cli.setup_logging`

### ISSUE THREAD

**Issue by OddBloke** [canonical/ubuntu-advantage-client#553]
We look for an existing handler or create our own, and we perform similar actions for each. Pretty low-hanging fruit for a refactor (but more than I wanted to do right now because there isn't test coverage).

**Comment by powersj** [comment]
We now have 4 CLI bugs open and I think this is the biggest of the 4. 

@OddBloke could you shed some light on what you might want to see changed? Possibly giving me something to do on the flight back :)

**Comment by OddBloke** [comment]
This specifically refers to the duplication here: https://github.com/CanonicalLtd/ubuntu-advantage-client/blob/925b85af49eb411cd5f49a2875061010a86ec863/uaclient/cli.py#L368-L381 So I think it's a relatively simple refactor.
