### ISSUE TITLE
`ua --version` should display the same output as `ua version`

### ISSUE THREAD

**Issue by OddBloke** [canonical/ubuntu-advantage-client#663]
```
$ ua --version
usage: ubuntu-advantage [command] [flags]
ubuntu-advantage: error: the following arguments are required: 
```

**Comment by OddBloke** [comment]
We should probably output the same as `ua version`:

```
$ ua version
19.4
```

**Comment by powersj** [comment]
Interesting the `--version` isn't complaining about not getting the version, it is the `ua` command is complaining that additional arguments are required and we give no suggestions.

For example:
```
multipass@t1:~$ ua --foobar
usage: ubuntu-advantage [command] [flags]
ubuntu-advantage: error: the following arguments are required: 
multipass@t1:~$ 
```

**Comment by OddBloke** [comment]
I've split the more general "weird output on unknown flag" out to #672. This issue is for implementing `--version` (which will cause the weird output to go away for this specific case), #672 is for fixing the general weird output issue.
