### ISSUE TITLE
Introduce integration testing on VMs

### ISSUE THREAD

**Issue by OddBloke** [canonical/ubuntu-advantage-client#855]
Currently, we only have support for testing in lxd containers. We have several services that are inert in containers, so we can't get full coverage using them.

**Comment by OddBloke** [comment]
For future reference, I had some thoughts about how to do this here: https://github.com/CanonicalLtd/ubuntu-advantage-client/pull/767#issuecomment-542834304

**Comment by OddBloke** [comment]
Related thoughts here: https://github.com/CanonicalLtd/ubuntu-advantage-client/pull/767#discussion_r336054352

**Comment by blackboxsw** [comment]
This is resolved in ad7a1241cc2b3cbbcb7a4a762caf9e91cc09d373
