### ISSUE TITLE
Add integration testing to master Travis runs

### ISSUE THREAD

**Issue by OddBloke** [canonical/ubuntu-advantage-client#856]
Currently, we run the behave integration tests in every Travis run, even though every test run is only testing the version of ubuntu-advantage-tools in the daily PPA. Currently, to give us a chance to observe the stability of the tests, we ignore failures. Until we're able to test the code in a PR (via #853), there's no point running the tests so often.

We can and should still run the tests for the master branch, even though they will be testing the daily PPA. This will still signal that regressions have occurred, even though it will be after they've landed in master, been mirrored to Launchpad and built into the daily PPA. This is still better than users catching the issues.

(This is distinct from integration testing in CI before changes land in master, because that has a _hard_ requirement on #853. We can also afford to take longer running tests on master, because they don't have an impact on developer throughput, meaning that #854 is less pressing.)

**Comment by powersj** [comment]
Did #887 close this?
