### ISSUE TITLE
Collapse same arches into a single name

### ISSUE THREAD

**Issue by panlinux** [canonical/ubuntu-advantage-client#917]
With https://github.com/CanonicalLtd/ua-contracts/issues/539, which is live in the staging contract server at the moment, the server has joined the architectures list of `dpkg --print-architecture` and `uname -m`. That means the ua client will get, for example, `i386` and `i686` for x86 32bits, and `amd64` and `x86_64` for x86 64 bits, and similar aliases for other arches.
When trying to enable a service on an unsupported architecture, the client will say it's not possible because the current architecture X is not in the list of supported architectures, and will then present this list, which will contain all the aliases.

For the esm-infra case on ppc64el, for example, we get:
```
root@trusty-ppc64el:~# ua enable esm-infra
One moment, checking your subscription first
ESM Infra is not available for platform ppc64le.
Supported platforms are: amd64, i386, i686, x86_64
```
We should probably collapse that list and only use one architecture name. In this case, it should be `amd64` and `i386`.
Note this server change is only live on staging, and things are still a bit in flux, but we thought best to file this bug as is looks like we are going ahead with that staging change.

**Comment by orndorffgrant** [comment]
Tracking in SC-1125
