### ISSUE TITLE
status: reports `unattached` while ua-client setup is still in progress

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#962]
UAClient attach operations can take upwards of 40+ seconds, on an auto-attach Ubuntu PRO platform, a user has a significant window of time during first boot where the machine will report unattached until livepatch snap gets installed, enabled and running before ua status is written, and properly reports the correct attached state of each service.

To remedy: 
 - we could write out status information during interim steps, it would at least show 'attached' earlier, though each defaultEnabled service would not yet show enabled until that step was complete
 - we could make the CLI a bit smarter to report something like `setup in progress` | `configuring` | `starting` until ua is done with setup.

**Comment by powersj** [comment]
Marking idea and adding to Misc milestone - essentially a wishlist item.

I recognize how this might help ensure a clean user experience, something we can tackle down the road though.

**Comment by renanrodrigo** [comment]
SC-1004 is done and this is fixed
